### ISSUE TITLE
/re 2 goes to /re ? 2 as well.

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#125]

**Comment by cyberpwnn** [comment]
Im not sure i understand. You mean the tabulation?

**Comment by CaptainAmpersand** [comment]
Literally just typing /re 2 does exactly what /re ? 2 does

**Comment by cyberpwnn** [comment]
Yes, /re defaults -> /re help
/re help is the same as /re ?

So /re [2] -> /re help [2]-> /re ? [2]
