### ISSUE TITLE
Problem with Sticky Pistons

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#135]
Fast running Sticky Pistons are sometimes dropped after being unlocked.
Demonstration: https://i.imgur.com/Bqip3Em.gif

React-6.26120a
PaperSpigot 1.10.2

**Comment by Rbot48** [comment]
React-6.26411a is somehow affecting the machine used in the demonstration, and it no longer works as a clock.

**Comment by cyberpwnn** [comment]
Can you post both config.yml and config-experimental.yml please?

**Comment by Rbot48** [comment]
Sure! I don't think I changed anything, though.
config.yml: https://pastebin.com/PTY833vd
config-experimental.yml: https://pastebin.com/0gwuekd7

**Comment by Rbot48** [comment]
This issue persists with React 6.0.48.

**Comment by cdmvirt** [comment]
This issue is causing major issues for all out doors, machines etc
