### ISSUE TITLE
Cull entities not working

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#145]
Command: /re act cull-entities not working.
Mobs & Stacked mobs are not culled by RAI too.
http://prntscr.com/i41bef

Server Version: Paperspigot 1.8.8

**Comment by cyberpwnn** [comment]
I have found a temporary fix.
Remove the @Prefer and @Defer stuff in the cull rules. That will fix it for now.

**Comment by cyberpwnn** [comment]
Fixed in 6.32691a
