### ISSUE TITLE
Config Problem - Mob Stacking

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#146]
When you disable mob stacking, and you want to re-enable this, you can't.

EDIT: After a config change ( experimental config ) mobs are stacking again

**Comment by cyberpwnn** [comment]
What is the issue here?

**Comment by lucas2107** [comment]
Idk how can I explain it, so there is the steps to reproduce this:

- Start server with Mob stacker ON
- Change config, turn off mob stacker
- Re-enable Mob stacker ==> some mobs are not stacked

**Comment by cyberpwnn** [comment]
Mobs only stack when an entity is spawned near them. Are you sure that isnt the reason?

**Comment by lucas2107** [comment]
Idk :/ I'm going to try again
