### ISSUE TITLE
(Suggestions) Additions to commands

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#155]
Small things which would potentially look nice:

These are primarily simple use-of-command suggestions:
/re cpu for Cpu score
/react topchunk (Change to /re lagchunk?) Or, implement /re tc, /re top
/re subscribe [channel] -- Potentially show the channels the can subscribe to in the tooltip

(Small) Have the breaking of leaves via React disabled for default (I say, as I see these trees be destroyed so easily)

**Comment by cyberpwnn** [comment]
Implemented in 6.0.49
