### ISSUE TITLE
Easy way to see what you are subscribed to

### ISSUE THREAD

**Issue by zicy** [VolmitSoftware/React#157]
When using the command /re subscribe & /re unsubscribe would it be possible to add a green checkmark and/or red cross depending on which of them you are already subscribed to ?

The list i am talking about,
![image](https://user-images.githubusercontent.com/3398437/36064803-0a5f1bce-0e91-11e8-8c86-19f4ed3ef4b6.png)

**Comment by cyberpwnn** [comment]
Implemented in 6.0.50
![image](https://user-images.githubusercontent.com/10619135/36065634-7928e6a0-0e6b-11e8-9d9f-937cbd93ca53.png)
