### ISSUE TITLE
/re map show different CPU %

### ISSUE THREAD

**Issue by zicy** [VolmitSoftware/React#158]
Example with 4 maps in itemframes,
![image](https://user-images.githubusercontent.com/3398437/36072753-9606a8e2-0f25-11e8-8a59-8720dc4fc2a8.png)

Example with a map in main and of hand
![image](https://user-images.githubusercontent.com/3398437/36072773-f794e3ee-0f25-11e8-9327-545b4a9ec81b.png)

**Comment by cyberpwnn** [comment]
2 reasons for that

1. There is an average polling per renderer instead of the same average
2. Each time the cpu is polled is a new map being rendered meaning progressively the cpu usage is going up as it loops through the maps.

Ill see what i can do to make them the same number
