### ISSUE TITLE
/re f - ON/OFF changes are not saved after reload

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#161]
After running /re f, enabling or disabling one of the features and running /re reload, the changes are discarded. 
![Image](https://i.imgur.com/OvBodwg.png)

Same applies to [OPTIONS]:
![Options](https://i.imgur.com/gHGrFhG.png)

---
React v6.0.51
Tested with PaperSpigot and TacoSpigot 1.10.

**Comment by cyberpwnn** [comment]
Removed in PR-2
