### ISSUE TITLE
/re book - Server Spikes displaying duplicates

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#162]
Image:
![Server Spikes](https://i.imgur.com/gxcjQX3.png)

---
React v6.0.51
Tested with PaperSpigot and TacoSpigot 1.10.

**Comment by Sikatsu** [comment]
Same on normal spigot.

**Comment by cyberpwnn** [comment]
Fixed in 6.1.2

**Comment by relavis** [comment]
Appears to no longer be an issue
