### ISSUE TITLE
Fast Leaf Decay does not update blocks

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#166]
After breaking a tree trunk, you can hear the sounds of the leaves being broken, but the blocks stay there until you right click them or relog.
Demonstration: https://media.giphy.com/media/3ohs4oE5ghHUYuB74Q/giphy.gif

---
React v6.0.53
Tested with PaperSpigot and TacoSpigot 1.10.

**Comment by cyberpwnn** [comment]
Correct. It will update snow to destroy it, but that is the entire reason it is fast.

If you want leaves to decay faster WHILE updating blocks (the laggy part) then i guess ill add an option to not use NMS hooks

**Comment by cyberpwnn** [comment]
Added an option in the config to NOT use nms.
However i have also improved the fast block destruction to include vine checking
