### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#168]
React use 160% of my CPU: https://timings.aikar.co/?id=89285c461f1a44d3b6cd70d795f33af0

React version: 6.0.69
Running on Paper 1.8.8

**Comment by cyberpwnn** [comment]
Identified. Thread pool does not shut down until the next next reload. This means that if you are mapping then use /re reload, it will continue to render to a null map while the new map is rendering too.

**Comment by cyberpwnn** [comment]
#205
