### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Xuwznln** [VolmitSoftware/React#169]
I recently found that my servers with React will occupy more CPU usage. I tested 1.12.2 1.11.2 1.9.4 1.8.8 both with and without React. It will only take up 0.3% withou React but 5% with React. I tested server only with React 5.7.8 and older version but get the same problem. Really troubled by that. Hope to Fix ! Thanks!

**Comment by cyberpwnn** [comment]
#205
