### ISSUE TITLE
 Asynchronous Async Chunk Load sending error messages

### ISSUE THREAD

**Issue by master4life** [VolmitSoftware/React#185]
PaperSpigot: 1337 BUILD

I led react 6 pre-release 1 running over a day on my skyblock server. And over this time it kept sending messages about Async Chunk Loads errors.

https://i.imgur.com/ywBhlQM.png
https://i.imgur.com/dH4xrKl.png
https://i.imgur.com/KHsU4VD.png

Over and over again. With few hours differency.

**Comment by cyberpwnn** [comment]
Please paste text instead, its really hard to search up every node in an image

**Comment by cyberpwnn** [comment]
Fixed
