### ISSUE TITLE
React 6 Breaking Item frames that use maps

### ISSUE THREAD

**Issue by AeternumStudios** [VolmitSoftware/React#190]
Creating Image boards with the plugin BannerBoards results in blank maps even though BannerBoards is returning a success.
MC Version 1.12.2

**Comment by cyberpwnn** [comment]
Elaborate. How does this have to do with react? What is an image board. Why is react responsible for fixing it?

**Comment by cyberpwnn** [comment]
Fixed in 6.0.2
