### ISSUE TITLE
React FLD Ignores the do not decay flag

### ISSUE THREAD

**Issue by Sikatsu** [VolmitSoftware/React#193]
When I use leaves in my build and remove one, it removes all leaves. When I disable ''Fast Destroy'' it removes like 2-4 leaves instead of the one I actually remove.

**Comment by cyberpwnn** [comment]
Wait i understand now, React is ignoring the do not decay tag on leaves

**Comment by cyberpwnn** [comment]
Fixed in 6.0.2
