### ISSUE TITLE
Errors in console and React causing players to glitch

### ISSUE THREAD

**Issue by Ew9304** [VolmitSoftware/React#196]
Hello,

Today I decided to buy React, I am using the default config and running it on Spigot 1.8.8. After a few minutes I noticed errors in my console pointing to React. The first error received was "Failed to decay FastTickController" and I was advised to disable the decay in my React config.

Now I noticed that when players are shooting bows or fighting skeletons it will give an error in the console (not sure what is causing it) and after getting that error in the console (not sure if it is related to the error, but it is definitely related to React somehow) - the player will teleport to spawn for example or to the vote crates, and they will get glitched in the map, they won't be able to move and are glitching out, spawn isnt fully or not at all rendered in, and the player will eventually be kicked by my anti cheat (AAC) for "phase" or "not taking knockback" 

I know that this is caused by React somehow because I have been running this server for a year now and have never had any problems, I installed React today and all of a sudden there is all these problems. If I take React out of my plugins folder, all of these problems do not occur.

LOGS: http://paste.volmit.com/giqayiyepa.md

![react-3](https://user-images.githubusercontent.com/34957646/36862071-c850362e-1d53-11e8-8b54-eb9d969d6b49.png)
![react-1](https://user-images.githubusercontent.com/34957646/36862072-c85fd052-1d53-11e8-9bc0-0c06637dc4fe.png)
![react-2](https://user-images.githubusercontent.com/34957646/36862073-c871e15c-1d53-11e8-8dc8-f8e14c474070.png)

**Comment by cyberpwnn** [comment]
Please keep in mind that R6 has just come out, and you are using a version of minecraft released 4 years ago. 

* For fast decay, i would suggest turning off fast-decay (that is if you want decay) perhaps react cant get a good nms binding for fast block destruction
* For Arrows, i beleive it is the pickup status (as it diddnt exist in the bukkit api on 1.8) You can turn off despawn-useless-arrows under tweaks -> drops to prevent this from causing issues. What this does is despawn landed arrows which no player can ever pick up.

**Comment by Ew9304** [comment]
Hi okay sorry, I purchased React because I saw that it supported 1.8, and I also figured there would be less bugs in 1.8 since it has been around longer... Usually new products are more buggy (like the new version of React) 

Anyways I am not getting errors in the console for the arrows anymore after updating, but my players (and me) are still getting glitched out. Here is an example, I will /warp spawn, /warp crates, /warp spawn, /warp pvp, a few times until once I warp, I can tell I am at warp crates for example, but none of the blocks around me are loaded, I can't see anything and I can't move, I am glitched, Slowly shaking up and down because I am glitched, and then I will slowly start falling through the map until ground level, where I still cant move until I restart the server 
![react1](https://user-images.githubusercontent.com/34957646/36877961-d8c9026a-1d8a-11e8-8100-beff50fb8d8d.png)

**Comment by Ew9304** [comment]
https://www.youtube.com/watch?time_continue=122&v=T8OPcRQ66Uw
