### ISSUE TITLE
Entity Throttling and Tile Throttling don't work with PaperSpigot 1.10.2

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#198]
With Spigot 1.10.2, these features are available and say "Spigot/PaperSpigot". But when running the server with Paper 1.10.2, they both are disabled. 
![](https://i.imgur.com/Ggdy4Zb.png)
![](https://i.imgur.com/Ry9rUMd.png)
```
This server is running CraftBukkit version git-Spigot-de459a2-51263e9 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
```
```
This server is running Paper version git-Paper-916.2 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
```
React v6.0.4

**Comment by cyberpwnn** [comment]
Fixed in 6.0.5
