### ISSUE TITLE
Water Fluid is tripping

### ISSUE THREAD

**Issue by Sikatsu** [VolmitSoftware/React#199]
Lock Fluid is tripping. Players are reporting water is lagging and is stuck in the air: http://prntscr.com/ilm6w1

/re subscribe action spams messages about 2x Lock Fluid.

**Comment by cyberpwnn** [comment]
Disable it in config-experimental 
![image](https://user-images.githubusercontent.com/10619135/36883531-027c3b68-1da9-11e8-8015-f53b92bf63a6.png)

**Comment by Sikatsu** [comment]
Will disable it, but does that mean it's normal behaviour?

**Comment by cyberpwnn** [comment]
Fixed in 6.0.7
