### ISSUE TITLE
/re Filesize - Feature

### ISSUE THREAD

**Issue by Curtis73** [VolmitSoftware/React#202]
Add in /re fs/filesize from React 5 - it's a nifty command & would be a shame to lose it.

**Comment by cyberpwnn** [comment]
Perhaps also a way to check the size of worlds?

**Comment by Curtis73** [comment]
That'd definitely be useful for me - it'd save me having to download a world via FTP to see how big it is...

**Comment by cyberpwnn** [comment]
Added in 6.2 https://cdn.discordapp.com/attachments/402410294644834304/423781650451660800/unknown.png
