### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#205]
Timings: https://timings.aikar.co/?id=8bab47a6648046d2aa1c44b417e748d6
React Version: 6.0.5
Server Version: PaperSpigot 1.8.8 (latest build)
React::Task: surge.PluginAmp$3 (interval:1) <-- 86% of CPU load on lag spike
R6 is using 10% of a 3.8Ghz CPU (Xeon E3)

#194

**Comment by sannielollie** [comment]
Having the same issues on spigot since this morning

React v6.0.5 Total: 12.607 s Pct: 81.98%
with on top
67.17% 146.12% 849.91 s 73.06 ms 1.0 11.6k Task: PluginAmp$3(interval 1)

Unloading React makes the lagg instantly going away, but this is an anti-lag plugin, ironically :P

**Comment by cyberpwnn** [comment]
If anyone can pull up JMX monitoring when this is happening, it would help greatly.

**Comment by sannielollie** [comment]
That sounds like hocus pocus to me, how do i pull that off? Running on Windows btw ^^

**Comment by lucas2107** [comment]
https://timings.aikar.co/?id=7c9a9e6320f8458ea0d0363b35a7d88b

Is it a problem with Tiles Entities?

**Comment by Frerduro** [comment]
https://timings.spigotmc.org/?url=vebaquviso

**Comment by cyberpwnn** [comment]
@sannielollie its not hocus pocus, JMX monitoring is what i need to identify the issue, Google VisualVM
@lucas2107 only high thing i see in that is entity stack controller (2.4ms) which is not the issue it seems

**Comment by lucas2107** [comment]
http://prntscr.com/inced5 is that related?

**Comment by B4TT3RY** [comment]
I have same issues

Timings: https://timings.aikar.co/?id=5fe211fcc86e40368815359f219162a2

**Comment by cyberpwnn** [comment]
Yup i've identified it i believe. Its the sync queue.

**Comment by cyberpwnn** [comment]
Possible fix in 6.0.9 PLEASE TEST

**Comment by cyberpwnn** [comment]
Thanks @B4TT3RY a ton, just need confirmation its fixed!

**Comment by lucas2107** [comment]
Seems to be fixed with React 6.0.9
https://timings.aikar.co/?id=0b138f06b84847b090dfdfb2e7fc3c84
Paper 1.8.8

**Comment by cyberpwnn** [comment]
Ill keep it open for a bit longer for extra confirmation

**Comment by B4TT3RY** [comment]
My Timings: https://timings.aikar.co/?id=5eee81ffe7e94ac6b5acf0c79b73a2c7

**Comment by B4TT3RY** [comment]
Timings: https://timings.aikar.co/?id=7b99b39ffd8a4914981f061663d12589
I think my server isn't resolved
(sorry for my bad english!)

**Comment by cyberpwnn** [comment]
You would be correct sir, but i need a /re dump WITH timings to help find these issues (timings is mostly useless unless you want to know if there is lag or not) but /re dump gives me information on WHERE the problem is

**Comment by B4TT3RY** [comment]
[18:22:01 INFO]: [React]: ✔ Dumped: http://paste.volmit.com/usugilezax.json
[18:22:28 INFO]: View Timings Report: https://timings.aikar.co/?id=8f6dced31b634185bb932a6ef48cc95e

@cyberpwnn

**Comment by cyberpwnn** [comment]
Interesting, its the same problem (that i fixed) for some reason. Have you rebooted since you updated?
If you havent, i would say try that... But ill see what i can do.

**Comment by B4TT3RY** [comment]
umm.. just using plugman.
i'll reboot server soon

**Comment by cyberpwnn** [comment]
What version of minecraft is your server on?

**Comment by cyberpwnn** [comment]
Interesting, it might actually be pending tasks?

If you look at the map, scroll to the very bottom and check Sync Queue
What is the number? Screenshot if you can

**Comment by B4TT3RY** [comment]
i'm using PaperSpigot 1.12.2 (git-Paper-1339)

**Comment by B4TT3RY** [comment]
Now TPS is 9.. ;(
i'm unload React and TPS 20

**Comment by cyberpwnn** [comment]
Was that after reboot?

**Comment by B4TT3RY** [comment]
nope

**Comment by cyberpwnn** [comment]
I would test once that happens. I think parts of 6.0.8 are still loaded

**Comment by B4TT3RY** [comment]
oh ok i'll reboot wait :)

**Comment by B4TT3RY** [comment]
https://imgur.com/a/lasj2
i'm reboot but hellllll
React load TPS 10
React unload TPS 20

**Comment by cyberpwnn** [comment]
If ```React load TPS 10
React unload TPS 20``` was NOT happening this issue would not exist. 

Im assuming you tried to load it again.
* Unload the jar
* Change the jar to 6.0.9
* DONT LOAD IT
* Reboot

**Comment by B4TT3RY** [comment]
Thx! i'll do that

**Comment by B4TT3RY** [comment]
https://imgur.com/a/v802N
Dump: http://paste.volmit.com/voyafutexu.json

**Comment by lucas2107** [comment]
Run R6.0.9 for 15 minutes with timigs On, then paste timings pls

**Comment by B4TT3RY** [comment]
but too lagging...T^T
players saying can't playing

**Comment by lucas2107** [comment]
Then run timings for 5 minutes only

**Comment by B4TT3RY** [comment]
i'll try that

**Comment by lucas2107** [comment]
If you have any error, create a new issue

**Comment by B4TT3RY** [comment]
https://github.com/VolmitSoftware/React/issues/222
This issue

**Comment by Sikatsu** [comment]
@cyberpwnn 

Still pretty high timings on 6.0.9.

https://timings.spigotmc.org/?url=somiseveka
http://paste.volmit.com/equfofinuy.json

**Comment by B4TT3RY** [comment]
Timings: https://timings.aikar.co/?id=7da674994966440e88d493efcb199b06
Dump: http://paste.volmit.com/wahexafuco.json

VisualVM:
![image](https://i.imgur.com/KDP3ZOA.png)

**Comment by lucas2107** [comment]
"main.tp.sync": "AVG: 22.12797

A tick is 50ms, Sync queue is using 22ms/50, that's why React load is so high.

**Comment by B4TT3RY** [comment]
i think tp isn't problem
CPU: E5-2620 v4 vCore
Memory: 8GB (Spigot 5GB) 

Timings: https://timings.aikar.co/?id=886449e9aa844875af4808c50029b37c
Dump: http://paste.volmit.com/terobacuha.json

VisualVM:
![image](https://i.imgur.com/1BbV5kp.png)
When React Load, The value of the graph goes up quickly.
When React Unload, The value of the graph goes up slowly.
(Google Translate)

**Comment by cyberpwnn** [comment]
Cause was insane high tile entities (while not lagging the server on their own) reading the list frequently does. React now has a 0.25ms cap on how fast it can read the tile entities. The more tiles the slower the sampler updates the tiles (spreading the job across however many ticks needed to keep under 0.25ms)

**Comment by B4TT3RY** [comment]
@cyberpwnn 
I think my server isn't fix it
https://timings.aikar.co/?id=a743949bfc4e4e24b0474102386b18d0
i forget dump :(

**Comment by lucas2107** [comment]
@B4TT3RY We can't do anything without dump.

**Comment by B4TT3RY** [comment]
https://timings.aikar.co/?id=b52e2639a9b247d6bfdc0b0e9008916f
http://paste.volmit.com/fawewaliwa.json

**Comment by lucas2107** [comment]
main.tp.sync still high.

**Comment by lucas2107** [comment]
Fixed for me.

**Comment by cyberpwnn** [comment]
Re open if this is a probrem again
