### ISSUE TITLE
Verbose spam: CTick Shut Down

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#207]
http://prntscr.com/im8ztc

**Comment by cyberpwnn** [comment]
Is there anything in the console?
What version of minecraft? Spigot? Paper? What version of react?

**Comment by lucas2107** [comment]
Nothing in console
Paper 1.8.8
React 6.0.5

**Comment by cyberpwnn** [comment]
Fixed in 6.1.2
