### ISSUE TITLE
Droppers/Dispensers Issue with Redstone stabilization

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#208]
Droppers/Dispensers are dropping all there content when R6 try to stabilize Redstone:

https://youtu.be/4lH8B3p_Nh4

**Comment by lucas2107** [comment]
Temp fix: https://prnt.sc/im92mp
In config-experimental.yml

**Comment by cyberpwnn** [comment]
Must be the update block functionality. Ill fix it.

**Comment by cyberpwnn** [comment]
Fixed in 6.0.6
