### ISSUE TITLE
Beacon effects run out

### ISSUE THREAD

**Issue by Ironic8b498** [VolmitSoftware/React#209]
Beacon effects run out then regen 3ish seconds later I'm running Spigot 1.12.2 with react 6.0.5. Haste II, Speed II, Strength II, Resistance I, Regeneration also noticed sometimes they are not all there.

**Comment by Frerduro** [comment]
@Ironic8b498 is your tps stable 20 if you have /re mon enabled?

**Comment by Ironic8b498** [comment]
yes tps is stable 20 rest of numbers are 323m 882 1306

**Comment by cyberpwnn** [comment]
My guess is tile throttling. React might be slowing down tile entity tick rates, and the potion effect is wearing off before it ticks again. You could increase the threshold or just disable it in the config.yml

**Comment by Ironic8b498** [comment]
I tried to increase the max-time but after doubling it,it didn't help. so I disabled the tile

  tick-smearing:
    entities:
      enable: true
      max-time: 25.0
    tiles:
      max-time: 35.0
      enable: false

**Comment by cyberpwnn** [comment]
Did that fix it?

**Comment by Ironic8b498** [comment]
yes, beacon effects working right, Do I need the tiles to help with server loads?

**Comment by cyberpwnn** [comment]
If you have a lot of tiles it helps. Perhaps i can add a patch to beacons to extend the beacon time if you are in the range to compensate. For now though, this isnt a problem.

**Comment by Ironic8b498** [comment]
for now it's not a issue, all this lingo of tiles and other things that cause lag is all new to me.I was happy to see a quick easy for for my lighting issue I had. Just got one more issue with my old map not sure what it is thou, I know I can't push blocks with pistons in a section on my base. if I copy and paste the stuff in another location it works fine

**Comment by cyberpwnn** [comment]
Tile entities are blocks that have more than just a block id and meta id. They are blocks such as the following
* Signs (very low impact) store text and rotation
* Chests (very low impact) store items and double chest mode
* Item Frames (not really tiles but ... technically are hanging) store a single item stack
* Hoppers (high impact if used a lot) store items and tick very often to push items around
* Beacons (low impact) simply tick to give the potion effect to players nearby
* Additionally, Furnaces, Droppers, Dispensers, and a few others

To help with this problem, React will slow down the tick rate of tile entities to prevent them from killing the server (especially hoppers)
What this means is react may be slowing down tile entities as a whole, reducing the tick rates.
If the tick rates are reduced on beacons, that means 
* Beacon X will tick 1 time every second
* Potion effect lasts for 3 seconds
If react slows this down, it may end up like
* Beacon X slowed down to 1 time every 5 seconds
* Potion STILL lasts for 3 seconds
This means there are 2 seconds where the effect runs out and there is no tick yet.

I can fix this by increasing the potion effect time.
