### ISSUE TITLE
Don't work on Thermos

### ISSUE THREAD

**Issue by Scrik** [VolmitSoftware/React#211]
Version React 6.0.5 don't start and create plugins files

https://pastebin.com/TtAd6PpM

**Comment by Frerduro** [comment]
@Scrik could i have your server jar version?

**Comment by Scrik** [comment]
@Frerduro 
KCauldron version 1.7.10-R0.1-SNAPSHOT 
Build: KCauldron-1.7.10-1614.201

**Comment by cyberpwnn** [comment]
So i guess i just will stop knowing when entities spawn? EntitySpawnEvent doesnt exist in KCauldron. The project has not been worked on for a very long time.

**Comment by cyberpwnn** [comment]
#187
