### ISSUE TITLE
[ClearLag] Plugin Command (/lagg)

### ISSUE THREAD

**Issue by GalaxyEaterGR** [VolmitSoftware/React#215]
React is using the command (/lagg) and it's making the plugin [ClearLag] useless. Can you please do something for that ? because i use React and ClearLag on my server and i have this big problem

**Comment by Rbot48** [comment]
It seems like React is checking if the command starts with "lag" or "tps", I'm also having this problem. I have the command /tpserver [server], and react is overwriting it with the /tps command.

**Comment by cyberpwnn** [comment]
Fixed in 6.0.6

**Comment by cyberpwnn** [comment]
Re-Fixed in 6.0.7
