### ISSUE TITLE
Plugin freezes the server, react thaws it & then freezes

### ISSUE THREAD

**Issue by Curtis73** [VolmitSoftware/React#216]
![image](https://user-images.githubusercontent.com/14040165/36946026-788e573a-1fae-11e8-8ba3-7857a2fd75c6.png)

Title says it all

**Comment by Curtis73** [comment]
Throughout the lock or just generally?

**Comment by lucas2107** [comment]
Throughout the lock

**Comment by Curtis73** [comment]
I can see that ChatControl is a problem [](https://timings.spigotmc.org/?url=vavinoroge)

**Comment by cyberpwnn** [comment]
React is causing tick issues on occasion #205 But this is simply a warning about plugins.
