### ISSUE TITLE
Server crash with auto reload config

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#220]
Server crashed after a config change: http://paste.volmit.com/sojinezehe.md

**Comment by cyberpwnn** [comment]
It happened 6 seconds AFTER react finished loading the new config. Also, if react was responsible for it, it should have been in the exception. This is why logs have a timestamp :P

```
Spigot usually crashes due to Plugins
Paper usually crashes due to PaperSpigot
```
