### ISSUE TITLE
Serverlock if a player join after a long empty time?!

### ISSUE THREAD

**Issue by DaisukeVN** [VolmitSoftware/React#233]
**What happens?**
If a player login to the server after an undefined empty time the server TPS falls and the server get locked for 1-2sec. Then React show "The server has recovered from a lock!"

**Logs, Errors:**
https://pastebin.com/0LKirNR5 < Error in console
http://paste.volmit.com/iquvukobux.json < your new feature (/re dump)

**What I tried.**
Without the React-Plugin, everything works well.
After a long empty time if a player join, the TPS is still stable.
Only with React it drop fast and get locked.

**Which version do I use.**
6.1.1

**Comment by cyberpwnn** [comment]
This is not an error. It's a warning that the server is freezing. Which it was, and i see players complaining about the tps just before hand. 

React warns like that if the server freezes for over 7 seconds, so based off that, and the logs, looks like your server had a 7+ second spike

**Comment by DaisukeVN** [comment]
Okay but without React the server never has this Lock problem.
All works fine, chunks loading and nothing get locked.
With React all things stops till your plugin show it recovered the lock.

**Comment by cyberpwnn** [comment]
How do you know its locking if react isnt reporting it?

Do you have any actual monitoring or profiling of this?

**Comment by DaisukeVN** [comment]
I use BungeeTabListPlus. It can detect the TPS too and i've build it inside the tablist.
So after joining a press Tab to see the TPS. In the Tablist & your Monitor it drops.
Without React the Tablist stay 19~20TPS.

I'll try to catch the TPS drop with the Timings-Feature of Spigot.
Maybe it can help to find the problem.

**Comment by cyberpwnn** [comment]
That will help a ton. Also /re dump when it happens too

**Comment by cyberpwnn** [comment]
It could be the Garbage Collector (you mentioned a long time of no joins) in which case the only thing you can do there is increase your memory.

**Comment by DaisukeVN** [comment]
Okay. A the problem happen since React Version 6.0.0
Maybe i should try to use the old version.

**Comment by cyberpwnn** [comment]
For now perhaps. It's a full rewrite, it will improve over time :P

**Comment by DaisukeVN** [comment]
So...
Timings: https://timings.spigotmc.org/?url=xedivabefi
Yours: http://paste.volmit.com/pivafobunu.json

I can't find the problem... I tried to double the RAM but it still happen.
On another Server your plugin isn't installed but alle other Plugins. This Server runs fine after joining...

Argh this is.... Idk. :/

**Comment by cyberpwnn** [comment]
If react is warning you that the server spiked, that does not mean all of the sudden that react is intentionally locking your server.

It's impressive how misleading something so obvious can be. I will remove the feature.

**Comment by lucas2107** [comment]
Why removing the feature?
Add it to config and disable it by default :D

**Comment by cyberpwnn** [comment]
Added in 6.1.2

**Comment by DaisukeVN** [comment]
Hmm. I still have the problem. The Server not get lock anymore but stuck for some seconds.
The problem only happen if the server stay empty for a long time (~6h+) and a player join after this time.
I installed your plugin on my maintenance-server to test it and the problem only happen on this server.
All other server haven't this plugin 'till the problem get fixed. x)

The maintenance server has 10GB RAM and only 20 plugins. I think this is enough RAM to say it isn't the RAM? (Garbage Collecter) Ot should i give it 20GB to test it? xD

If you have an idea, tell me. I can do with this server what i want.

Your Dump
http://paste.volmit.com/lareruxila.json
