### ISSUE TITLE
Map closes on any player disconnect

### ISSUE THREAD

**Issue by Frerduro** [VolmitSoftware/React#234]
If someone leaves the server when you are using react map it gets disabled

**Comment by cyberpwnn** [comment]
I member

**Comment by Frerduro** [comment]
It was just a reminder :)

**Comment by cyberpwnn** [comment]
Modifying the buffered image would be too intense during render times. And caching it is an option i guess. 1.11 and below are buggy with certain colors for some reason.

**Comment by cyberpwnn** [comment]
Fixed in 6.543
