### ISSUE TITLE
React XP hotpickup not respecting config

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#235]
xp:
    fast-drop-xp: false
    fast-xp-pickup: false

Despite I had both settings set to false, even reloaded the plugin with Bile (since the fast reload didn't work), it still didn't work. Only unloading fixed the issue.

Spigot 1.12.2
React ver 6.1.1

**Comment by cyberpwnn** [comment]
Did restarting fix the issue? More specifically is this a hotload problem or is react actually ignoring the setting?

**Comment by CaptainAmpersand** [comment]
After checking it a few times, with several restarts, it still seems to be ignoring the fast-xp-pickup being set to false. Therefore I'm ruling out Hotloading issues :c

**Comment by cyberpwnn** [comment]
Ive checked the source. It is working how it should. Perhaps there is something wrong when loading the config. Try setting it to false next time you restart.

**Comment by cyberpwnn** [comment]
Fixed in 6.2
