### ISSUE TITLE
Super Sampler Spam & Possible Crash

### ISSUE THREAD

**Issue by LoXR** [VolmitSoftware/React#236]
Was told to revert back to react 5 due to these.

Whats happend?
In the console it had spammed this:
[08:44:45] [Server thread/INFO]: React: Super Sampler did not start correctly. Resetting
[08:44:48] [Server thread/INFO]: React: Language: enUS

And shortly after it had crashed my server with this in the crash reports.
Crash report: https://pastebin.com/2XBN1XkJ

**Comment by lucas2107** [comment]
Duplicate of #222

**Comment by cyberpwnn** [comment]
It's a standard paperspigot crash. Maybe it saw a ghost.
