### ISSUE TITLE
React Monitor shutdown if server is lagging

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#238]
When the server start to lag, React monitor shut down and I need to reload the plugin to see it again.
It's the same for React actionlog, it freeze and I need to reload React to unfreeze this.

React 6.1.2
Paper 1.8.8

**Comment by lucas2107** [comment]
Crashing randomly too

**Comment by cyberpwnn** [comment]
Pretty sure 6.2 Fixes this we i will see
