### ISSUE TITLE
React monitoring Freeze

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#241]
Frozen since 6 hours: http://prntscr.com/iro6qj

Monitoring system freeze after few minutes. Need to reload React to fix.

**Comment by cyberpwnn** [comment]
Any method of reproduction? See if you can cause it again

**Comment by lucas2107** [comment]
Just launch scoreboard/monitoring and wait ^^

**Comment by lucas2107** [comment]
https://youtu.be/MVePfogdcH0

**Comment by cyberpwnn** [comment]
Yup, been fixing it.

**Comment by cyberpwnn** [comment]
Fixed in 6.2.1
