### ISSUE TITLE
React failed to receive PacketPlayInKeepAlive

### ISSUE THREAD

**Issue by EthanTG** [VolmitSoftware/React#243]
http://paste.volmit.com/raw/bekebipixi

Happened only one time after a kick with AdvancedBan.

Issue #242 is missing more than half the error (I'm bad at copying) :/

also it's my error so nobody take credit
---
+1 if you've had similar issues or support me

**Comment by lucas2107** [comment]
duplicate of #242

**Comment by Puretie** [comment]
Continuation of #242

**Comment by cyberpwnn** [comment]
Protocollib Version
Minecraft Version
Spigot? Paper? What is the flavor?

**Comment by cyberpwnn** [comment]
Fixed in 6.2.1

**Comment by EthanTG** [comment]
you apparently answered your own questions :P
