### ISSUE TITLE
Improve /re top or /re lagchunk

### ISSUE THREAD

**Issue by Joe7670** [VolmitSoftware/React#250]
When using /re top or /re lagchunk the ms of lag in the chunks change so quickly that if you spam the command different chunks will come up every time (I'm spamming it a couple times a second here). I think this is because the window of time used to calculate how many ms of lag there is in a chunk is too small. Perhaps increase the window? Or have the option to.

**Comment by cyberpwnn** [comment]
I have increased the window from a factor of 1.25 to 1.01 (very small reduction)

This will increase the values to very high numbers, but it should get the milliseconds a bit more stable. The only downfall to this is if all physics stop, it will take 10 seconds or so for the number to actually get to it's true value (0 in this case)

Implemented in 6.2.2
