### ISSUE TITLE
Error causes React 6.2 to disable on server restart

### ISSUE THREAD

**Issue by Guddina-tim** [VolmitSoftware/React#251]
Running Spigot 1.12.2

`16.03 04:17:38 [Server] INFO [React] Disabling React v6.2
16.03 04:17:38 [Server] WARN [React] Plugin React v6.2 generated an exception while executing task 14456
16.03 04:17:38 [Server] INFO org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
16.03 04:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bd30843]
16.03 04:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:144) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bd30843]
16.03 04:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleAsyncRepeatingTask(CraftScheduler.java:140) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bd30843]
16.03 04:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleAsyncDelayedTask(CraftScheduler.java:114) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bd30843]
16.03 04:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleAsyncDelayedTask(CraftScheduler.java:97) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bd30843]
16.03 04:17:38 [Server] INFO at com.volmit.react.util.A.<init>(A.java:10) ~[?:?]
16.03 04:17:38 [Server] INFO at com.volmit.react.controller.PhysicsController$2.<init>(PhysicsController.java:181) ~[?:?]
16.03 04:17:38 [Server] INFO at com.volmit.react.controller.PhysicsController.onTickAsync(PhysicsController.java:180) ~[?:?]
16.03 04:17:38 [Server] INFO at com.volmit.react.controller.PhysicsController$1.run(PhysicsController.java:122) ~[?:?]
16.03 04:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bd30843]
16.03 04:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-9b8bba4-bd30843]
16.03 04:17:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
16.03 04:17:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
16.03 04:17:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
16.03 04:17:38 [Server] INFO [React] Enabling React v6.2
16.03 04:17:38 [Server] WARN [React] Task #5934 for React v6.2 generated an exception
16.03 04:17:38 [Server] INFO java.util.ConcurrentModificationException: null
16.03 04:17:38 [Server] INFO at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:907) ~[?:1.8.0_151]
16.03 04:17:38 [Server] INFO at java.util.ArrayList$Itr.next(ArrayList.java:857) ~[?:1.8.0_151]
16.03 04:17:38 [Server] INFO at com.volmit.react.ReactPlugin$4.run(ReactPlugin.java:139) ~[?:?]
16.03 04:17:38 [Server] INFO at com.volmit.react.util.Task$2.run(Task.java:55) ~[?:?]
16.03 04:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bd30843]
16.03 04:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-9b8bba4-bd30843]
16.03 04:17:40 [Multicraft] Skipped 57 lines due to rate limit (30/s)`

**Comment by lucas2107** [comment]
Please paste it on http://paste.volmit.com/

**Comment by cyberpwnn** [comment]
#240
