### ISSUE TITLE
Feature request - Entity activation ranges

### ISSUE THREAD

**Issue by Joe7670** [VolmitSoftware/React#252]
Instead of having just one entity activation range in spigot which affects all mobs, have a feature which allows you to select multiple entity activation ranges depending on the mob.

**Comment by cyberpwnn** [comment]
I was also thinking about dynamic ranges too depending on the density of mobs. If you have 30 mobs
 that are 100 blocks away, none of them will activate

If you move to 50 blocks away from 30 of them, perhaps 5 of them will activate, the closer you get (by the time you are 10 blocks away) all of them will be activated.

**Comment by cyberpwnn** [comment]
I tried this a long time ago. It diddnt benefit that much. Instead i am using entity throttling which slows down the tick rate based on activation range. Works much better.

**Comment by Joe7670** [comment]
What about if I want separate ranges for different mobs though? Slimes for example, for slime farms?

**Comment by cyberpwnn** [comment]
There would be literally no point. React throttles entities so they are basically inactive unless they need to be anyways. 

Perhaps per entity activation range? Not sure how hacky that's going to be though.
