### ISSUE TITLE
Server crash since React 6.2

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#253]
My server is crashing since I updated React to 6.2: https://hastebin.com/ahutitopaw.css

Crash report: https://hastebin.com/azolegoqik.lua
Paper 1.8.8

**Comment by cyberpwnn** [comment]
Are you sure this is caused by react?

**Comment by lucas2107** [comment]
This happened when I updated to React 6.2 and players was reporting a bug with entities :/
So i don't rly know.
