### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by sannielollie** [VolmitSoftware/React#254]
Getting this error: https://pastebin.com/EHnrt87H

Recent changes: Updated to latest React version
Updated to spigot-1.12.2-R0.1-SNAPSHOT-b1610 (before the update it was running on spigot-1.12-R0.1-SNAPSHOT-b1372)

If u need more info let me know :)

**Comment by lucas2107** [comment]
Duplicate of #240 

Would be fixed in 6.2.1
