### ISSUE TITLE
Mob stacking respond to looting enchantments 

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#256]
Mobs Loots are bug, like in the video: https://www.youtube.com/watch?v=HiLwfpNlF0Q&feature=youtu.be
X7 stacked spiders

It's not only happening with enchanted items, it was just to show it correctly.

**Comment by cyberpwnn** [comment]
What is the issue? Is it not dropping anything? or not dropping the full loot.

**Comment by lucas2107** [comment]
sometimes it's dropping, sometimes it's only dropping when you kill the last mob but you get only 1 loot.

**Comment by cyberpwnn** [comment]
I need reproduction steps. In the sense of how to cause it. Step by step, then what you see happening so i can see if i get the same result and fix it,

**Comment by lucas2107** [comment]
To reproduce:

Stack mobs (How much u want) --> kill them.
That's very random, all players are reporting this problem with mob stacker. And I tried it, like in the video.

**Comment by cyberpwnn** [comment]
Ive got a couple lambs to sacrifice to the gods of rng, so ill hopefully find it in no time.

**Comment by lucas2107** [comment]
Fixed.
