### ISSUE TITLE
React GUI

### ISSUE THREAD

**Issue by haeiven** [VolmitSoftware/React#257]
Now, a lot of plugins are doing that.
Add a React GUI ( /re gui ) to control actions, etc... (maybe add server informations, etc...)

**Comment by cyberpwnn** [comment]
From #350 
> Hey,
What happened to the "/re act" GUI, it was a lot more friendly and could even expand this into doing a whole "/re settings" command where you config the config lol in a GUI.

**Comment by relavis** [comment]
I believe this was readded with `/re act`, please reopen if incorrect
