### ISSUE TITLE
Hole in world

### ISSUE THREAD

**Issue by Darko266** [VolmitSoftware/React#260]
![29261930_754262344771087_2589568106405822464_n](https://user-images.githubusercontent.com/20874142/37565155-17a17f0a-2aa4-11e8-835e-84fc0d4877ad.jpg)

This happend to me with the latest version of React (6.2.1)
When i removed the React plugin then the hole was not showing anymore...

**Comment by lucas2107** [comment]
And if you add React again? This is maybe a spigot bug who just need a restart to be fixed.

**Comment by Darko266** [comment]
Yes if i add it again the hole will be here

A restart won't help, i tested it out

**Comment by cyberpwnn** [comment]
What was in that chunk

**Comment by Darko266** [comment]
Well, other blocks of the spawn

**Comment by cyberpwnn** [comment]
Actually, what IS in that chunk (its clientside)

I can do literally nothing with a sideways picture of a missing chunk section.

Do you have Fawe?

**Comment by Darko266** [comment]
Yes i have Fawe

**Comment by cyberpwnn** [comment]
Use /re fix chunk while inside of it and looking down

**Comment by cyberpwnn** [comment]
Have you used /re a fix-lighting?

**Comment by Darko266** [comment]
I will try to do that.

No i didn't

**Comment by Darko266** [comment]
/re fix chunk fixes the issue but when i walk into that chunk i start slowly falling thru blocks

**Comment by cyberpwnn** [comment]
And im guessing you are on 1.8?

**Comment by Darko266** [comment]
Yes, 1.8.8

**Comment by cyberpwnn** [comment]
You could try causing it to happen

Section yourself off into a chunk
//chunk
//walls 20

Make a redstone clock with a few wires going places (keep it in that chunk)
Then when in side of this area use /re a lock-redstone @c:this @t:2s

**Comment by Darko266** [comment]
Yes, the chunk happend again

**Comment by Darko266** [comment]
And then with /re fix chunk it is fixed

**Comment by cyberpwnn** [comment]
Alright i see the issu

**Comment by Darko266** [comment]
Great

**Comment by Darko266** [comment]
If the update 6.2.4 should fix my issue, it didn't :P

**Comment by cyberpwnn** [comment]
It was an attempt to fix an issue i have no idea how to reproduce or find out what would cause it. I cant do much here without a way to reproduce it. I currently have 1.8 with R6 and Fawe, it isnt happening.

**Comment by JavituRec** [comment]
Without fawe:

![buggchunkkk](https://user-images.githubusercontent.com/10663192/37982968-4e7356fc-31f2-11e8-9b09-94a712706f41.png)
![rrrrrrrrrrr](https://user-images.githubusercontent.com/10663192/37982970-50d5fab2-31f2-11e8-8f99-5c4393f2594e.png)

**Comment by lucas2107** [comment]
Still happening on latest spigot 1.8.8 & latest TacoSpigot 1.8.8 @cyberpwnn

**Comment by Acenox** [comment]
Hello, Do you have news about this bug? I can not use React 6.0 because of this bug, thank you :)

**Comment by lucas2107** [comment]
You can use PaperSpigot as a temp fix. Idk why, but it's not happening on paper.
@Acenox

**Comment by cyberpwnn** [comment]
Or update to a version without critical bugs, performance issues and security flaws.

**Comment by cyberpwnn** [comment]
Wait... is multiverse + react causing it? I might be able to reproduce this! hah!

**Comment by cyberpwnn** [comment]
### Multiverse + React is causing it on 1.8.8 (spigot)
![image](https://user-images.githubusercontent.com/10619135/39885052-abfc4642-5459-11e8-854a-47b86144bed2.png)

**Comment by JavituRec** [comment]
Yes, I sent him a server, I do not know if you remember him. And exactly, you are using multiverse and react. Because in paper not ocurr?

**Comment by cyberpwnn** [comment]
Well this is the hard part... Trying to find the cause or if react is even the problem here. Im running through actions and attempting to cause different things in react to see if i can identify what is triggering it. No luck yet

**Comment by JavituRec** [comment]
For now I am using paper. I hope you find the cause, good luck.

**Comment by cyberpwnn** [comment]
> Hey, my problem is since i installed React on my Server the Chunk 0 ~ 0 is always a ghost chunk! I tried to fix this with React but it didn't work. So I dan't use React on my Server.

**Comment by cyberpwnn** [comment]
Can someone try turning on safemode NMS and safemode CHUNKS to see if it fixes the issue?

**Comment by Darko266** [comment]
I can

**Comment by Darko266** [comment]
Still happening on spigot, paperspigot and tacospigot.

**Comment by cyberpwnn** [comment]
Did you turn on the safe modes? Because if you did, react isnt capable of causing it. Besides, ive seen this happen without react on 1.8 alone.

**Comment by lucas2107** [comment]
Seems to be fixed on Taco 1.8.8

Trying on prod server.

**Comment by lucas2107** [comment]
Fixed on prod server.

**Comment by lucas2107** [comment]
Not fixed

**Comment by cyberpwnn** [comment]
React isnt causing this. 1.8.8 has a lot of bugs in it, but there is a reason it isnt being fixed. Can you guess why?
