### ISSUE TITLE
Eggs from chicken

### ISSUE THREAD

**Issue by Azeimin** [VolmitSoftware/React#264]
Stucked chicken (x5 for example) don't give you x5 eggs.

I think there is two ways to decide this problem:

1.  Speed up egg spawning in proportion to count of chickens
2. Just increase number of eggs for stucked chickens

**Comment by cyberpwnn** [comment]
Increasing the number would be more efficient. Alright

**Comment by cyberpwnn** [comment]
There is no way to 100% know where an egg came from since bukkit doesnt exactly have anything for that. Im going to close this for now but ill reopen it if i find anything that can make a cleaner solution

**Comment by cyberpwnn** [comment]
Refer to #352 for progress

**Comment by SwiftSwamp** [comment]
Closed as this was implemented.
