### ISSUE TITLE
FastLeafDecay not working on Paper 1.8.8

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#266]
FastLeafDecay isn't working on Paper 1.8.8

An other problem, If I want to set leaves with worldedit, leaf decay isn't working. I tried to enable/disable FastLeafDecay, refresh blocks... If I disable React, it's working.

**Comment by cyberpwnn** [comment]
So you want fast leaf decay to destroy those leaves?
And it started working when you DISABLED react?

**Comment by lucas2107** [comment]
Vanilla leaf decay isn't working when I set leaves with worldedit, but it's working without react.

**Comment by cyberpwnn** [comment]
Are there any errors?

**Comment by lucas2107** [comment]
No errors in console, juste spamming "Failed to tick FastLeafDecay" in R6 verbose.

**Comment by cyberpwnn** [comment]
Fixed in 6.3.1 (bukkit api diddnt support something to check if a leaf could be decayed)
