### ISSUE TITLE
Plugman support

### ISSUE THREAD

**Issue by Sikatsu** [VolmitSoftware/React#268]
The wiki states you could use plugman (which was possible with React 5), however it doesn't work with React 6. Easy to reproduce, just try to reload the plugin with plugman.

**Comment by cyberpwnn** [comment]
Works perfectly with PlugMan
![image](https://user-images.githubusercontent.com/10619135/37654007-15384306-2c17-11e8-8926-17100f2ddf3c.png)

Also works with BileTools
![image](https://user-images.githubusercontent.com/10619135/37654030-2708879e-2c17-11e8-9351-9d1315931ac9.png)

**Comment by Sikatsu** [comment]
Never heard of BileTools, is it some new sort of plugman? Can't find it on spigot either.

Anyway, in my case it gives an error on enabling (can't get it at this point)

**Comment by cyberpwnn** [comment]
What error
