### ISSUE TITLE
Conditional Reactions

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#270]
Add conditional reactions, like:

If there is more than 70 players connected turn on hoppers reactions
If there is more than 100 players turn on redstone reactions, etc...

**Comment by cyberpwnn** [comment]
Is #262 not good enough?

**Comment by lucas2107** [comment]
This will be a plus, idk if it's useless.. x)

**Comment by cyberpwnn** [comment]
Added a config value for Rai Activation default is 18.5. Playercount is not a good method for activating. It would be something like... Only start culling entities after the entity TICK time is over a limit.

Option added in 6.3
