### ISSUE TITLE
Different TPS?

### ISSUE THREAD

**Issue by EthanTG** [VolmitSoftware/React#271]
I have both Essentials and React. When I do /tps in game, it shows TPS according to React, but when I do it in console, it spits out Essentials' averages. Is that normal?

i liked it when it showed both :/

**Comment by lucas2107** [comment]
React is current tps when u do /tps

Essentials is average tps the last minute.

**Comment by EthanTG** [comment]
@lucas2107 

But it's a different output in console and in game which shouldn't be happening?

**Comment by lucas2107** [comment]
React isn't overwriting Essentials in the console. I think it's a good thing ^^

**Comment by EthanTG** [comment]
Yes, but what if I can't use console at a certain time or someone wants to check the average TPS of the server and also the exact TPS in game?

**Comment by cyberpwnn** [comment]
https://en.wikipedia.org/wiki/Average
