### ISSUE TITLE
React Lasts Versions Chunks Buggy

### ISSUE THREAD

**Issue by JavituRec** [VolmitSoftware/React#272]
Hello,

I have been testing the latest current version of React and everything seemed to be correct. Today I have passed this photo:

![skype_picture](https://user-images.githubusercontent.com/10663192/37827991-d81da396-2e99-11e8-88eb-3d70dcbdefcd.jpeg)

a chunk is invisible and is not the only one there is more in other worlds. I went to the forum and saw that another user reported the same bug.

I have not tried previous versions.

React dump: http://paste.volmit.com/agicusodoy.json
Server version: 1.8.8
React version: Last (6.2.3)

**Comment by cyberpwnn** [comment]
Im assuming you have FAWE installed? Try /re fix chunk (while inside of it)

**Comment by JavituRec** [comment]
Yes, I have FAWE

After try command /re fix chunk

![buggyc](https://user-images.githubusercontent.com/10663192/37829762-a8db4bcc-2ea0-11e8-909d-17e0fd6a2c55.png)

the chunk buggy yet

**Comment by JavituRec** [comment]
Today I have installed react in my skyblock server and in spawn and chunk buggy

![me_bugie_en_skyblock](https://user-images.githubusercontent.com/10663192/37845111-020d84de-2eca-11e8-865c-daa18e2bf8ff.png)

**Comment by cyberpwnn** [comment]
You have to be inside the chunk

**Comment by cyberpwnn** [comment]
I cannot reproduce it on 1.8. Any steps to causing it?

**Comment by JavituRec** [comment]
After use command inside, now entire spawn is bug

![chunkrr](https://user-images.githubusercontent.com/10663192/37845933-60a8f7b0-2ecc-11e8-8bb2-b1f881869fd3.png)

![cunhkk32](https://user-images.githubusercontent.com/10663192/37846010-8e3fcc08-2ecc-11e8-9e19-32bdfd82cc66.png)

I don't know how does it happen.

**Comment by cyberpwnn** [comment]
Its just packets by the way, Im doing all i can trying to guess what it is, but I do know that fawe causes this to happen a lot.

You could try to use /re a fl @c:this+4

**Comment by JavituRec** [comment]
The command worked for the moment, not bug chunk around the spawn. It is possible that there is some conflict between react and fawe. I know that fawe in old versions created some bugs of pieces in the distance but never empty a chunk like in the images.

**Comment by JavituRec** [comment]
it's curious in faction the command did not work

![ccccc](https://user-images.githubusercontent.com/10663192/37846594-5ad52780-2ece-11e8-8c6b-fa4119aef809.png)

**Comment by cyberpwnn** [comment]
Its not that there is a conflict,, 90% of the problem is that you are using a very old version of minecraft, and it makes it difficult to support. I cant do anything unless i can reproduce it. Try disabling rai

**Comment by JavituRec** [comment]
My server version is 1.8.8

Try with fawe and a world already loaded before installing react.

**Comment by cyberpwnn** [comment]
I have seen this happen with fawe alone, its what uses fawe or interacts with it. Continue this on #260
