### ISSUE TITLE
/re glass directly related to dropping tps

### ISSUE THREAD

**Issue by Joe7670** [VolmitSoftware/React#273]
I've only tested this for this /re glass "glass/block" option where you can see the changes through glass blocks, however I can without a doubt say this is definitely causing drops in TPS. When at a players end farm which utilizes a lot of hoppers (nothing major) you can see all the multiple block updates with glass, however the TPS drops very very low to like 8-15 very badly, then immediately after turning /re glass back off in the configuration, the TPS goes straight back up to 19-20

**Comment by cyberpwnn** [comment]
Im assuming you have a lot of hoppers? Perhaps i will "throttle" the capturing of events then.

**Comment by cyberpwnn** [comment]
Fixed in 6.3
