### ISSUE TITLE
server lockup.

### ISSUE THREAD

**Issue by Ironic8b498** [VolmitSoftware/React#275]
if no one has been o the server for a few hours server locks up and takes 30 seconds or so to recover. sometimes it crashes. https://www.spigotmc.org/go/timings?url=pasexenuqu I turned timings on yesterday, today I log into the server after if been empty overnight, froze up and when server was back to normal I ran timings paste. I run Spigot 1.12.2 and /ver says I'm 4 version behind.

**Comment by cyberpwnn** [comment]
Did react notify via chat or console what caused it? Did you turn off the monitor server option in the config?

Timings dont show it by the way. 

Pretty sure it was just gc.

**Comment by Ironic8b498** [comment]
no,in chat sometimes it says it removed from locked, or the server don't recover and crashes

**Comment by Ironic8b498** [comment]
complete logs from midnight to 6:30am.
https://www.hastebin.com/uxunuxumuj.sql

This is what I see it chat most of the time;
![mar-27](https://user-images.githubusercontent.com/6716130/38024327-aa823868-3252-11e8-9976-4e424df3be69.png)

Server is Offline on Bungee network 1.12.2,here is a list of Plugins
https://www.hastebin.com/lewoqeroja.css

**Comment by cyberpwnn** [comment]
Are you sure it was react and just not a long gc?

**Comment by Ironic8b498** [comment]
well server don't respond to anything, I can move player on client side but it don't really move on server side, no commands work until I run /tps and wait 30 or less seconds then it recovers, works normal after that. if I run 5.7.9 no issues on any of my servers

**Comment by lucas2107** [comment]
Try updating to latest spigot, maybe something is wrong on your version

**Comment by Ironic8b498** [comment]
I updated Spigot again last night still getting the server lockup
![faction-spigotupdate](https://user-images.githubusercontent.com/6716130/38135475-49cc58b0-33e6-11e8-97fe-c42d72300fd6.png)

**Comment by cyberpwnn** [comment]
I still need a timings report or at least a /re dump 

And i still think it's gc. This is exactly what gf causes

**Comment by Ironic8b498** [comment]
gave a timings report in the beginning, guess I forgot to turn timings back on after the crash yesterday. here is a dump http://paste.volmit.com/cehagiliwu.json

**Comment by cyberpwnn** [comment]
Update, you are way out of date
