### ISSUE TITLE
React 6 chunk event

### ISSUE THREAD

**Issue by WindUnwaken** [VolmitSoftware/React#276]
https://hastebin.com/eyibofowem.md

I don't have this error when using R5.
Please check if R6 break some plugins, such as slimefun, stackmob

If I can't link others plugins here, please closed this ticket, just want to let you know what plugin I used.
https://dev.bukkit.org/projects/slimefun
https://www.spigotmc.org/resources/stackmob.29999/

**Comment by cyberpwnn** [comment]
```
at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$49.generateEnergy(SlimefunSetup.java:3200)
```

SlimeFun
