### ISSUE TITLE
Entities culling problem

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#277]
Sometimes, entities culling isn't working.

When it's happening on big servers, tps drop:
TPS from last 1m, 5m, 15m: 13.88, 17.65, 19.08

Video: https://youtu.be/vSZ8Fsyibs4

**Comment by cyberpwnn** [comment]
You have 13,000 tile entities. React doesnt cull tile entities.

**Comment by lucas2107** [comment]
As you can see in the video, when I run /re act purge-entities,

The server stop lagging.

**Comment by cyberpwnn** [comment]
I diddnt see the frames were low lol You might be able to change the activation. ive added an option to change the activation tps now and added comments for everything in 6.3
