### ISSUE TITLE
ConcurrentModificationException Crash

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#281]
Logs: http://paste.volmit.com/pijexijofu.pl

**Comment by lucas2107** [comment]
Please provide us server version

**Comment by Rbot48** [comment]
CraftBukkit version git-Spigot-de459a2-51263e9 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
React v6.3

**Comment by cyberpwnn** [comment]
Confirmed 1.10 doesn't play nice with r6 with fast leaf decay. I'll default async off and add an option for it in the config

**Comment by cyberpwnn** [comment]
Fixed in 6.3.2
