### ISSUE TITLE
Feature Request - /re chunktest <time>

### ISSUE THREAD

**Issue by VeilStar** [VolmitSoftware/React#282]
Using '/re chunk' to check for lag in a chunk currently seems to display a snapshot of real-time values (with a curve?), which isn't very useful when you want to get a good idea of how much lag things in a certain chunk actually cause overall, since one moment a lot might be happening, while the next moment nothing is happening. Generally speaking I seem to get very varying results when using the command (in non-static environments). Which is why I propose something a bit different; /re chunktest < time >.

Using '/re chunktest 20s' for example would log everything react currently displays in /re chunk every game tick for a total of 20 seconds or 400 game ticks, then avarage the results of those 400 gameticks, and display that to the user. Somewhat similar to running a timings report.

**Comment by cyberpwnn** [comment]
I like this a lot because i have had people ask to average MORE so the numbers reflect over time without notice... But this reduces accuracy. People have also asked for less averaged values which wouldn't show the "gist" and would only show the current tick. 

Yeah i will add this in within the next week. Thanks for the idea!

**Comment by Joe7670** [comment]
Adding on to this, it'd be even better if you could somehow test multiple chunks at once as sometimes something is causing lag in an area consisting of multiple chunks.

**Comment by cyberpwnn** [comment]
@c:this+4 (this chunk + radius of four)

**Comment by cyberpwnn** [comment]
Added in 6.3.2

```/re a cb [@c] [@t]```

Benchmark My chunk + 2 radius for 5 seconds
```
/re a cb @c:this+2 @t:5s
```

Benchmark the entire nether for 20 seconds
```
/re a cb @c:!*&world_nether.* @t:20s
```

Benchmark the chunk area im looking at and ignore my chunks (radius of 3) in the selection. Usage is described in the actions page (/re act)
```
/re a cb @c:look+2&!this+3 @t:2s
```

**Comment by Joe7670** [comment]
Question: When I use the command for multiple chunks, it seems to be dividing the average ms values by the number of chunks so instead of giving the average ms values for all the chunks together, it's giving the average ms per chunk. Is that what was intended?
