### ISSUE TITLE
React when monster Coexist is monster walk slow and lag attack

### ISSUE THREAD

**Issue by hallday0024** [VolmitSoftware/React#283]
when monster Coexist is monster walk slow and lag attack
I want to not monster is walk slow and lag 
NO server lag :)

**Comment by Frerduro** [comment]
Could i have a timings report of your server?

**Comment by hallday0024** [comment]
No report for PL

**Comment by cyberpwnn** [comment]
1. Turn off entity throttling in react config under tick smearing 
2. In timings reports send the links anyways (click show all at bottom)
