### ISSUE TITLE
Feature request - Timings for individual players

### ISSUE THREAD

**Issue by Joe7670** [VolmitSoftware/React#287]
Be able to benchmark how much lag each player on the server is taking up by looking only at what chunks they have loaded. I think this is what /re blame is meant to do but all of the time it shows me Server: 100%
Instead of that could we have something similar to what /re top shows us? With the laggiest player at the top. Clicking on the player would then teleport you to that player.

1. A command like /re blame @t:10s (Benchmarks everyones chunks loaded for 10 seconds)
2. Also a command which can just check an individual player - /re blame <player> (unsure of what paramaters is best)

All of this is assuming you're able to tell who has which chunks loaded. I'm okay with overlapping values (say if everyone was in the same chunk so they all loaded the same chunks, so every player would be the laggiest player with everyone having identical ms of lag for each category)

If you're able to implement this, then I would use this command a lot to check who is the player who constantly puts the most strain on the server and then i'd be able to investigate why... see they have built too many automated farms, too many entites or etc..

**Comment by cyberpwnn** [comment]
The chunk blame feature seems to not be working currently. Ill fix that first then work on this. Thanks for the amazing suggestion

**Comment by relavis** [comment]
`/re blame` has been removed as there is no reliable way to determine who is loading the chunks.
