### ISSUE TITLE
Servercrash after a long empty time (still)

### ISSUE THREAD

**Issue by DaisukeVN** [VolmitSoftware/React#294]
Hey Guys.

After some update the problem is still not fixed. Now my server generates a crashlog.
Hopefully it can help you to find the problem or maybe you can tell me what the problem is.
:/

Thank you

**Comment by lucas2107** [comment]
Can we have logs?

**Comment by DaisukeVN** [comment]
Ops. Forget. https://pastebin.com/pjTECjPU

**Comment by cyberpwnn** [comment]
Are you using /react scoreboard at all?

**Comment by DaisukeVN** [comment]
Never used it. Only /react map. Idk what /react scoreboard does.

**Comment by lucas2107** [comment]
[21:12:41] [Spigot Watchdog Thread/ERROR]: Current Thread: Netty Epoll Server IO #0
[21:12:41] [Spigot Watchdog Thread/ERROR]:  PID: 52 | Suspended: false | Native: false | State: BLOCKED

Seems to be Netty threads crashing.

What is your server version & React version?

Try running your server behind a bungee (if you can). (Don't miss to set bungeecord: true in bukkit.yml)

**Comment by DaisukeVN** [comment]
The Server Version is: git-Spigot-b6ecf3b-1daee53 (MC:Implemented API version 1.12.2-R0.1-SNAPSHOT)
React Version last crash (this crash) was 6.3.2. Now I've 6.3.3 installed.

The Server already is behind a Bungee.
bungeecord: true (in spigot.yml)
connection-throttle: -1 (in bukkit.yml)
online-mode=false (in server.properties)

I've 5 servers on 1 root-server. 4 normal Server and 1 Maintenance/Update-Server (Test-Server)
Before I install a plugin to all servers, I check the plugin on the maintenance-server first.
All 4 servers run perfect and very smooth (without React) except of the maintenance-server since i've installed react (Ver.6.X). Version 5.X ran perfectly.

The crazy thing is... If I stay online 1h, 2h, 4h, 12h, 1day. Nothing happen. Everything works fine.
If I leave the server and rejoin after some hours, the TPS drops hard.
The longer I stay offline the more it takes to get back stable.

Little example:
1~6h > 1-5sek drop
6~12h > 5-10sek drop
1 day > ~10sek
+1day > crash

Without React. I can stay 1 week. All works fine. (My 4 normal Server)
Hopefully you understand what I mean. My english isn't that good. xD

**Comment by HexedHero** [comment]
I'm honestly having the same issues, after 7 hours its unplayable.

**Comment by cyberpwnn** [comment]
I smell memory & gc issues
