### ISSUE TITLE
Add Perms for /React Dump/Filesize

### ISSUE THREAD

**Issue by HexedHero** [VolmitSoftware/React#296]
Hey,

These can leak a lot of information about the server and I think you should add perm nodes for them do you can give players access to all of react but not them commands!

**Comment by cyberpwnn** [comment]
The people who have access to react should be 100% trusted with any information. React players are classified by 2 categories only, react perms, and no react perms.

However i have added it anyways for additional control.
react.systeminfo
It is now required for anyone to use /re filesize or /re dump in 6.3.4
