### ISSUE TITLE
Setting can't go above 12000

### ISSUE THREAD

**Issue by HexedHero** [VolmitSoftware/React#297]
# The interval at which chunks are purged. Only chunks OUTSIDE of every
    # player's view distance combined are purged.
    purge-interval: 12000

if you put any number higher than 12000 it resets back to 12000, I wanted to run my Purge every 15 mins but have to do it every 10.

**Comment by cyberpwnn** [comment]
Purge interval maximum value extended to 720000 ticks (1 hour)
