### ISSUE TITLE
Graphic Issue with React Map

### ISSUE THREAD

**Issue by HexedHero** [VolmitSoftware/React#300]
https://i.gyazo.com/ff49b0e9fa8c5ff8b8d231db9f00996e.png
This happens every so often when the servers been online for a while.

**Comment by cyberpwnn** [comment]
,,, Interesting values there. Is it showing up on the scoreboard or somewhere else too? Or just the map?

**Comment by HexedHero** [comment]
https://i.gyazo.com/967c46fafd832a79c0fd9783ea8e983c.jpg

**Comment by cyberpwnn** [comment]
The super sampler is having trouble reading the tick i guess.

**Comment by cyberpwnn** [comment]
This is related to #329 the same thing is causing it.
