### ISSUE TITLE
React regions 

### ISSUE THREAD

**Issue by cyberpwnn** [VolmitSoftware/React#307]
Support region selection with a react wand and optionally support world edit wand selection. 

Region settings and flags include 
* NO_ACTION - selectors cannot select this regions chunks 
* NO_STACKING - mob stacking is disabled in this region 
* NO_SAMPLE - Disables physics sampling in the regions chunks

**Comment by lucas2107** [comment]
Can you add a flag like: NO_REACT
who disable Actions, stacking & sample? :)

**Comment by cyberpwnn** [comment]
I can't really disable sampling without seriously slowing down the sampler thread... which needs to be lightning fast. But yes. Stacking is a form of an action so it would work.
