### ISSUE TITLE
Snow on trees

### ISSUE THREAD

**Issue by AzDreamerr** [VolmitSoftware/React#308]
Hello! After leaves from felled tree disappearing, snow, which  was on the leaves remain. Please, fix it

**Comment by lucas2107** [comment]
Hi,

Provide us server version & React version.

**Comment by AzDreamerr** [comment]
React 6.3.1
Minecraft 1.11.2

**Comment by cyberpwnn** [comment]
Fast leaf decay is fast. It does my updated neighbor blocks. You can then this off

**Comment by cyberpwnn** [comment]
In config.yml under fast leaf decay turn off fast block destruction
