### ISSUE TITLE
Feature Request - Discord Notifications Channel (Webhook)

### ISSUE THREAD

**Issue by PerkusMaximus** [VolmitSoftware/React#311]
React 6 could support Discord notifications from RAI and other subscription systems for an external use for staff that aren't online but have access to Discord.

They could specify a webhook link inside the configs which you could feed all the RAI notifications through instead of a bot to join the server.

You could also embed certain levels of RAI. High Priority alert could be red while a minimum alert could be yellow or something.

An optional option in the config could be for sending additional alerts like whenever someone activates the purge command, it'll send the details of the result, who activated it and so on in it's own embed color.

**Comment by cyberpwnn** [comment]
We could just go for a bot. That would at least allow you to use commands directly to the server.

**Comment by PerkusMaximus** [comment]
What about both? I'd like to have the feed not the functions. Would make both sides happy.
