### ISSUE TITLE
Feature request: console subscription

### ISSUE THREAD

**Issue by SlimeDog** [VolmitSoftware/React#312]
Please support console subscription to channels.

Channel monitoring in-game has two deficits:

1. It requires that the admin/op be in-game
1. It disappears quickly
1. The RAI issues I want to monitor are already concluded by the time I can connect, after rebooting the server.

Console monitoring would be recorded for later review. Of course, it should be off by default, to avoid console/log spam, but available should the server operator desire.

In order to address (3), make it a configuration option, for each available channel. Something like:
```
log-channels-to-console:
  rai: true
  ...
```
That is the only way to monitor the actions taken immediately after server restart.

**Comment by SlimeDog** [comment]
It is clear that React-AI 6.3.4 has resolved the TPS drop on one of my servers, most likely caused by spawn-area entities (ie., in a loaded chunk). This feature might allow me to identify the cause with certainty.

**Comment by cyberpwnn** [comment]
Implemented in 6.3.5

![image](https://user-images.githubusercontent.com/10619135/39017072-50dc2ed6-43f0-11e8-8f66-9f03a19e6965.png)
![image](https://user-images.githubusercontent.com/10619135/39017126-66e5a48c-43f0-11e8-92ed-684dac0b0930.png)

**Comment by SlimeDog** [comment]
Thanks. Much appreciated.

**Comment by SlimeDog** [comment]
Please add
```
console:
  verbose: true|false
```

**Comment by lucas2107** [comment]
look at the screens pls

**Comment by SlimeDog** [comment]
The screen represents verbose:true. I will test for verbose:false.

**Comment by SlimeDog** [comment]
I see that verbose is one of the channels that can be sent (or not) to the console. Thanks.
