### ISSUE TITLE
Feature request: Prefix configuration

### ISSUE THREAD

**Issue by SlimeDog** [VolmitSoftware/React#314]
React 6.3.4 and previous

Please support configuration of the in-game and console/log prefixes. I would like the ability to remove colors, specifically -- ie., I would prefer unencumbered "[React]" -- but general string configuration would be ideal.

**Comment by cyberpwnn** [comment]
Do you mean console colors?

Tags are generated with a few properties... if you like i can add an option to strip formatting and color from console logs?

I can also add some options for coloring the brackets and the actual name of the prefix (react) Is that all you need?

**Comment by cyberpwnn** [comment]
![image](https://user-images.githubusercontent.com/10619135/39017673-e49841a4-43f1-11e8-8edb-ea2285116d73.png)
![image](https://user-images.githubusercontent.com/10619135/39017687-eb586230-43f1-11e8-932b-7dbeb97cbd32.png)

**Comment by SlimeDog** [comment]
That would address the console. I also would like to set the in-game prefix. So perhaps in addition:
> prefix: '[React]'

with whatever default formatting codes you choose.

**Comment by cyberpwnn** [comment]
When you buy adidas shoes, do you want to change the logo on them too? 

I have two reasons why i dont want to / have not yet done this.

### 1 Technical "additions"
The react tag is dynamic. I cant just load in a string and make it work how it works now. Example 
![image](https://user-images.githubusercontent.com/10619135/39825614-2e602b2e-5380-11e8-919b-d3c1186e2198.png)

### 2 It's React
It isnt any other plugin. React is React, so React should have a tag called React. Your players should never see that tag anyways. I don't see why people have a problem with the name or the tag. What is wrong with it? 

I know a lot of people who enjoy taking other peoples plugins and renaming them even though they diddnt spend any time putting in the work to make the damn thing. If you want to change the name for that reason, then decompile it yourself and change it, You dont ask adidas to change their own logo on your shoe for you. 

If its for some other reason, for example the color, or bracket formatting, we can work something out, but i dislike the ability to change the name.

**Comment by SlimeDog** [comment]
There is no nefarious intent. I don't want to change the brand. I want to control the formatting.

I appreciate that devs (or Adidas) want to promote their products with colors and highlights and etc. However, I prefer no adornments, just the straight brand name. Especially in the console/log, which player's never see, but also in-game.

Interestingly, _React_ is the only plugin to which I have made this request that has resisted.

**Comment by SlimeDog** [comment]
I agree that React is "React".

**Comment by cyberpwnn** [comment]
You can already turn off console color

The reason is it isnt a 5 second change if you want to change the tag like you demonstrated in your example, it takes a lot longer to do that because of how react uses tags. Ive been working on the color changes and more but it requires me to go through everything just for this small (visual) feature. 

Meanwhile mob stacking doesnt work how intended and performance could always be better.

**Comment by SlimeDog** [comment]
I have never asked for immediate address of my request; it's a _request_. I respect your priorities, particularly wrt mob stacking.

**Comment by cyberpwnn** [comment]
Not sure what you want if its not just removing color

**Comment by SlimeDog** [comment]
Removing color and any format (bold, italic, etc) would be excellent.

**Comment by cyberpwnn** [comment]
Just to be sure.... you want ALL color removed?

**Comment by cyberpwnn** [comment]
![image](https://user-images.githubusercontent.com/10619135/39887369-0f7badc4-5460-11e8-8584-08046569678b.png)

**Comment by cyberpwnn** [comment]
Most commands will work with this, but some may not without a lot of work. Ill release this portion for now, but just know some parts may not be complete yet as there is no one-trick button i can press to stop coloring everything. especially tellraw stuff (that was hard lol)

**Comment by cyberpwnn** [comment]
Implemented in 6.5.4

**Comment by SlimeDog** [comment]
Thanks. Very nice looking (to my eye).
