### ISSUE TITLE
[Console spam] Big console spam

### ISSUE THREAD

**Issue by maxlehot1234** [VolmitSoftware/React#315]
Hi everyone, I just want to know why I get this issue since few days sometimes.
https://paste.powerplugins.net/babenufara.sql

It was spam the console A LOT and cause more issues than without this spam.

If you have an idea for this, let me know please since I will not uninstall an anticheat from my server...

Sometimes, it was cause by Autosell (clip), sometimes, it was TokenEnchant (vk2gpz) and now it was AacAdditionPro (Anticheat) Not the best plugins to remove.

Thanks a lot and have a nice day/night

**Comment by cyberpwnn** [comment]
You can turn it off in the main config.
