### ISSUE TITLE
lang/enUS.properties overwritten

### ISSUE THREAD

**Issue by SlimeDog** [VolmitSoftware/React#319]
React 6.3.6

lang/enUS.properties rewritten, thereby deleting my edits.

**Comment by lucas2107** [comment]
What was your version before you update?

**Comment by cyberpwnn** [comment]
What is missing.
What were your edits.

**Comment by SlimeDog** [comment]
Apologies, I reflexively typed _config.yml_ previously. I meant _lang/enUS.properties_.
Previous version is irrelevant. Reproduction:
- Edit _lang/enUS.properties_, changing
```
rai.event-message.react1=Running %1 to help with %2
rai.event-message.react2=Running %1 to fix %2
rai.event-message.react3=Running %1 again to fix %2
```
- /react reload
- Note that file is overwritten with original values.

**Comment by cyberpwnn** [comment]
Please copy the lang file, and change it. enCustom or something then specify that name in the config.
