### ISSUE TITLE
Tile smearing breaks redstone 

### ISSUE THREAD

**Issue by Frerduro** [VolmitSoftware/React#325]
Tile smearing seems to break hopper clocks.

**Comment by cyberpwnn** [comment]
There is no way for me to reproduce this without any situation given or reproduction steps
Tile entities are not part of redstone so I don't understand how this would break redstone without any examples

**Comment by cyberpwnn** [comment]
If you dont like it turn it off, i cant make things work perfectly and throttle them at the same time
