### ISSUE TITLE
Bugged chunk at world made with MultiVerse

### ISSUE THREAD

**Issue by onemoreplays** [VolmitSoftware/React#334]
Hello,
so today I made world with MultiVerse (not only one actually) and this happened on every single one.
https://www.youtube.com/watch?v=dbgqx0nPZVg
As you can see, when I disable React and reload world, chunk is okay.
Hopefully you will be able to repair it.
Thanks and have a nice day,
inao

**Comment by lucas2107** [comment]
Duplicate of #260
