### ISSUE TITLE
Stacked mobs high hp

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#341]
Stacked mobs don't want to die :/

Paperspigot 1.8.8
React 6.5.3

**Comment by cyberpwnn** [comment]
Correct 
![image](https://user-images.githubusercontent.com/10619135/39884583-523643b6-5458-11e8-868b-514cb541b32c.png)
https://minecraft.gamepedia.com/Blaze

**Comment by lucas2107** [comment]
Stacked mobs are just invincible.

**Comment by lucas2107** [comment]
#342 ==> https://www.youtube.com/watch?v=fI15n7RE8LQ&feature=youtu.be

Bugs:

* Stacked mobs are invincible
* Mobs despawn randomly
* Falling Mobs are glitched when they die

**Comment by cyberpwnn** [comment]
Does this still happen on the latest version? Im pretty sure i fixed it.

**Comment by cyberpwnn** [comment]
Fixed in 6.543

**Comment by lucas2107** [comment]
Still not fixed in 6.544

https://streamable.com/u1z63 (Reported by M8wqp6Sl11)

**Comment by cyberpwnn** [comment]
Does anyone have reproduction steps? Because i cannot reproduce it.

**Comment by lucas2107** [comment]
Use paper 1.8.8 @cyberpwnn

**Comment by cyberpwnn** [comment]
Fixed in 6.552
