### ISSUE TITLE
Stacked mobs invincible and death bug

### ISSUE THREAD

**Issue by user4592** [VolmitSoftware/React#342]
Stacked mobs can't die and sometimes disappear, and if they die to fall damage they glitch out 
Paper spigot 1.8.8
https://www.youtube.com/watch?v=fI15n7RE8LQ&feature=youtu.be
Also, is there a way to disable the mob stacking feature temporarily and is there an option for interval clear lag/items?

**Comment by lucas2107** [comment]
Duplicate of #341
