### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by HexedHero** [VolmitSoftware/React#344]
What happened to seeing how much of the RAM plugins use compared to players?

Would be amazing if we could see how much RAM each plugin is using etc.

**Comment by lucas2107** [comment]
If I remember it's not possible.

**Comment by cyberpwnn** [comment]
The current idea is to attempt to cram jmx into react to find out that information

**Comment by lucas2107** [comment]
This can be very helpful for people who don't know how to use java profilers to detect memory leaks.

I hope this is possible, but I think it's complicated :/ Good luck cyberpwn ^^

**Comment by cyberpwnn** [comment]
Pssst 
![image](https://user-images.githubusercontent.com/10619135/40513773-c2d8eb1a-5f74-11e8-8ad8-fafb6e70e729.png)

**Comment by cyberpwnn** [comment]
Implemented in 6.548
