### ISSUE TITLE
Stack attributes and stack issue.

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/React#345]
e.g. stack babies with other babies and stacking specific colours of sheep together. E.g. blue sheep with other blue sheep and armoured mobs with other armoured mobs.

Currently it stacks mobs causing potential issues. For example baby pigs will stack with adult pigs and vice versa. 

ISSUE: Stacks are also lost when saving the config. (Not sure about restarts haven't tested yet but it should also remove stacks on restart if this is the case)

**Comment by cyberpwnn** [comment]
It "forgets" about stacks if the chunk is unloaded, react is reloaded or the server is shut down.

**Comment by LogGits** [comment]
Persistent stack sizes is really important. A config option would be amazing. Why does it forget about the stack size? Doesn't react set the mobs living entity customName?

**Comment by cyberpwnn** [comment]
Well if you forget about the stack size, you have zero chance of corrupting your own stack data (accidentally create weird stacks), reduce the chance of overstacked herds of animals, reduce memory usage, and improve startup time.

I will add a configuration option for persistent stacks though, as i can see the use in it.

**Comment by LogGits** [comment]
Im not too sure how it would corrupt stack data, as you are storing the actual data about the mob in its custom name. This custom name doesn't get removed by default. Thus, you can pull the information out of the mobs customname. Granted, if this is really an issue, you can check if the mob stack size is greater than the defined stack limit in the config to circumvent any possible issues. Thank you for understanding. I recently purchased this plugin and I am really liking it so far. Keep up the great work!

**Comment by cyberpwnn** [comment]
Entity stacks are now cached by default with auto defragging enabled (so you dont end up with 2 billion entities that have not existed for months) in 6.543. Cache is stored in `React\cache\stack-cache.ulf`

**Comment by cyberpwnn** [comment]
Refer to #352 for progress attributes
