### ISSUE TITLE
Clickevent Suggest_Command for /react commands

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/React#348]
A cool feature would be if you could make the react commands inside`/react` clickable. A click event suggest_command would put the command into the players chatbox. This is more of a quality of life improvement.

**Comment by cyberpwnn** [comment]
Are you talking about tab completion?

**Comment by cyberpwnn** [comment]
... Then what is #347

**Comment by cyberpwnn** [comment]
Ohhh, text suggestions, yeah sure ill add that in.
