### ISSUE TITLE
Action/Settings GUI

### ISSUE THREAD

**Issue by HexedHero** [VolmitSoftware/React#350]
Hey,

What happened to the "/re act" GUI, it was a lot more friendly and could even expand this into doing a whole "/re settings" command where you config the config lol in a GUI.

**Comment by cyberpwnn** [comment]
It felt dirty and messy due to all of the configs. Ill see what i can do.

**Comment by cyberpwnn** [comment]
Dah dupe, Check #257 for progress on this.
