### ISSUE TITLE
Entity Attributes for mob stacking

### ISSUE THREAD

**Issue by cyberpwnn** [VolmitSoftware/React#352]
* Don't stack adults and babies
* Don't stack sheep with different colors
* Chickens should drop more eggs (risky and may never happen but still)
* Sheep should drop more wool when sheared (PlayerShearEntityEvent)

**Comment by LogGits** [comment]
in terms of sheep and chicken dropping multiplied wool and eggs, if this is added, it would be amazing if it was optional/configurable in config.

**Comment by cyberpwnn** [comment]
The issue with eggs and sheep is that the only way to currently do it (without very risky ... and dirty hacking) is to literally check when an egg item is spawned (or wool item) then figure out who dropped it, and see if there is a sheep nearby... or chicken and hope to god it was the right one lol

**Comment by LogGits** [comment]
The only downside of PlayerShearEntityEvent is that you cant modify the drop, you could cancel the drop and spawn in the item at the location.

As for Chicken eggs yeah that would be the case. ItemSpawnEvent or something like that. Maybe a really small proximity? Another plugin used this for eggs: https://github.com/Pwn9/PwnChickenLay/blob/master/src/com/pwn9/PwnChickenLay/PwnChickenLayItemSpawnListener.java

**Comment by cyberpwnn** [comment]
Implemented in 6.564
