### ISSUE TITLE
Ping & TPS rounded placeholders

### ISSUE THREAD

**Issue by TheWranger** [VolmitSoftware/React#355]
- Placeholder for player ping
- Placeholder for rounded raw TPS (Rounded to 2 decimals)
- Placeholder for rounded raw ping

**Comment by lucas2107** [comment]
#274 I'm not sure this was added, try it.

**Comment by TheWranger** [comment]
Placeholders don't seem to work.

**Comment by cyberpwnn** [comment]
https://www.spigotmc.org/resources/placeholderapi.6245/

![image](https://user-images.githubusercontent.com/10619135/40268291-b86da638-5b38-11e8-9314-ed82d62a7ecf.png)

**Comment by cyberpwnn** [comment]
I have also added new suffixes 

### You can use the following suffixes for samplers
```
_raw -> Raw digits up to 9
_raw_0 -> Raw, no decimals
_raw_1 -> Raw, 1 decimal
_raw_2 -> Raw, 2 decimals
_raw_3 -> Raw, 3 decimals
_raw_4 -> Raw, 4 decimals
_raw_force_1 -> Raw, forces 1 decimal. If the value is round, places 0.
_raw_force_2 -> Raw, forces 2 decimals. If no decial is set for any segment, zero is used. I.e. 19.00 (instead of 19)
```

Implemented in 6.544

**Comment by Frerduro** [comment]
yay

**Comment by TheWranger** [comment]
@cyberpwnn We still need a rounded up ping placeholder
![image](https://user-images.githubusercontent.com/24642838/40269083-65c3348c-5bbc-11e8-8447-e6670979f79d.png)

**Comment by lucas2107** [comment]
%react_ping_raw_0% @TheWranger

**Comment by cyberpwnn** [comment]
No, either ping or ping_raw. Read the permissions.txt

**Comment by cyberpwnn** [comment]
Ill add more formatting.

**Comment by lucas2107** [comment]
Working for me: https://prnt.sc/jqenf5

**Comment by TheWranger** [comment]
![image](https://user-images.githubusercontent.com/24642838/40892222-5104c692-67d7-11e8-8db8-4f3f8af538a3.png)

**Comment by lucas2107** [comment]
Just %react_ping%

**Comment by TheWranger** [comment]
@cyberpwnn This still needs to be added.
%react_ping% Shows a decimal point with it and is very limited.

**Comment by cyberpwnn** [comment]
Refer to #412 for remainder of issue
