### ISSUE TITLE
Fast drop xp breaks mending

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/React#359]
set `fast-drop-xp: true` in the config. Kill a mob and it wont increase a mended tool's durability (try with damaged elytra). When this value is `false` mending works fine.

**Comment by cyberpwnn** [comment]
Correct because it removes xp orbs. There is no way to fix mending while still getting the benefit of this option. Its not intentional, but there isnt much to do. This is for lower versions or server which dont care about mending in exchange for higher performance. Think UHC, Mob farms etc.
