### ISSUE TITLE
Tamed mobs despawning

### ISSUE THREAD

**Issue by blazex224** [VolmitSoftware/React#375]
Hello,
There is an issue with tamed mobs despawning on my server, and I feel it has something to do with this plugin's compatibility with [MythicMobs](https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/), since it seems the only mobs despawning are tamed mythical mobs.
I am submitting a ticket to the MythicMobs plugin authors as well.
Thanks for the plugin!

**Comment by cyberpwnn** [comment]
In the config.yml under culling rules, do you have `@Refuse Tamed'?
