### ISSUE TITLE
Fast leaf decay causing high tick times

### ISSUE THREAD

**Issue by wulfwuud** [VolmitSoftware/React#377]
timings w/ online - https://timings.aikar.co/?id=6bebe81e470c4dc09ccc82c96d4be2d0 
timings w/out online - https://timings.aikar.co/?id=8e5e0b0a9fd5479190eb9ba4a9f7bafe

timungs w/out online after restart - https://timings.aikar.co/?id=b969a3090cff4165a0b5d0cb1a33d9a1

core - git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
cpu - Intel I7-4790K 4GHz
plib - 4.3.0

**Comment by cyberpwnn** [comment]
Can you use `/re a dump -f`

Also can you turn off fast leaf decay in the config to see if that is the issue?

**Comment by wulfwuud** [comment]
safemode-networking: true so no dump
i'll try turning off fastleafdecay if issue would shows again

**Comment by cyberpwnn** [comment]
Why do you have safemode net on?

**Comment by wulfwuud** [comment]
feature was added to plugin so i use it 
safety measures maybe

**Comment by cyberpwnn** [comment]
It only applies to react, and it is more of a signal to tell react dont bother using net as (perhaps the server is offline etc)

I would keep it on unless you have a legitimate reason (as the config warns)

**Comment by cyberpwnn** [comment]
Fixed in 6.554
