### ISSUE TITLE
MythicMobs With Purging

### ISSUE THREAD

**Issue by HexedHero** [VolmitSoftware/React#382]
Hey,

I have bosses on my server that didn't used to get purged but they do now, I think there should be MythicMobs support under purge in the config to not purge custom mobs or not, because it has it own command to purge mobs anyway.

**Comment by cyberpwnn** [comment]
Working on mythic mobs support 
![image](https://user-images.githubusercontent.com/10619135/40979060-bb5ee5ce-68a2-11e8-9e0b-76c8bffb877a.png)

**Comment by cyberpwnn** [comment]
Implemented in 6.555
