### ISSUE TITLE
Purge entities

### ISSUE THREAD

**Issue by fyrmftw** [VolmitSoftware/React#384]
Hey,

Is it normal for purge entities to purge tamed and named mobs and is there an option to disable that since I want to purge mobs on the server but I dont want it purging players tamed/named mobs.

Thank you

**Comment by cyberpwnn** [comment]
Tamed and named mobs are rules for culling. Culling is automatic, React never automatically uses purging. The purge command is like killall in essentials. 

Use `/re a pe @e:pig&cow` or something to specify what you want to kill.

**Comment by cyberpwnn** [comment]
Why purge? Culling was created for this specific reason. Culling automatically reduces entity clusters to prevent too many entities on a very fine degree of accuracy. 

Besides, removing too many entities can be bad too. It releases a bunch of memory, which causes java to gc, and use up more cpu, then bukkit spawns in more anyways. 

Culling aims to remove the excess or to... shave off the top to prevent spikes, and to prevent bukkit from re-spawning them in.

**Comment by fyrmftw** [comment]
Alright and this maybe a bit off topic but for focusing on fixing lag, do you recommend switching to the new react or staying with react 5, for like tps performance

**Comment by cyberpwnn** [comment]
React6 is more effective. Its just different, and people dont like different. So try them out, and pick one.

**Comment by fyrmftw** [comment]
Alright brilliant, thank you (: and for everything you do
