### ISSUE TITLE
react exessive tick usage tripple in a row!

### ISSUE THREAD

**Issue by wulfwuud** [VolmitSoftware/React#386]
timings - https://timings.aikar.co/?id=6ac9b79bf10340099093e28730636a0f
map - https://cdn.discordapp.com/attachments/189665083817852928/454247744995983362/unknown.png
dump will be in discord pm

**Comment by cyberpwnn** [comment]
So AAC is using 20% of your tick, and react is using 1%. Help me understand what your issue is.

**Comment by lucas2107** [comment]
On timings React is 23%
AAC is 20% ( This anticheat is... bad )

**Comment by cyberpwnn** [comment]
You mean this? 
![image](https://user-images.githubusercontent.com/10619135/41189154-5cf50d68-6b97-11e8-819e-d8b3f16d029c.png)
Yeah i skipped over that because it's a spike, not constant usage. It's average is under a millisecond.

**Comment by lucas2107** [comment]
http://prntscr.com/jsuhh5

**Comment by cyberpwnn** [comment]
Correct, you have just found a spike, not constant lag. It seems like that only happens 1-5% of the time
![image](https://user-images.githubusercontent.com/10619135/41327066-04b85d3e-6e90-11e8-94e5-d88d0420a816.png)

**Comment by cyberpwnn** [comment]
This is not excessive. This is normal usage with some spikes. Every timings report i have seen has more constant usage than react does.

If you are having a performance problem, then report it, but if you just look at react and see a high number, but ignore the fact that it isnt constant (i.e. 1.07% of the time) then dont report it.

There are a lot of things timings will add to plugins including gc spikes, which you cant really do anything about from the plugin side.

Unless you have a report which shows me react has MORE total time than the server tick dont report it.
