### ISSUE TITLE
React purging list not working

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#389]
I removed villagers from purging list and they still despawned when I run entities purge.

React 6.558
**Paper 1.8.8**

**Comment by cyberpwnn** [comment]
Did you use -f? https://brains.volmit.com/react/have-a-question/actions/purge-entities#using-the-force

**Comment by lucas2107** [comment]
No

**Comment by cyberpwnn** [comment]
Fixed in 6.559
