### ISSUE TITLE
Confirmation action on Purge Entities

### ISSUE THREAD

**Issue by fyrmftw** [VolmitSoftware/React#391]
Hey,

This is just a suggestion and I know that I can just disable the whole purge ability in the config, but is it possible at all to have a confirmation on Purge Entities (/react act purge-entities), since I don't want someone or even myself, to accidentally forget to specify what to purge when doing the command and wipe all mobs from our server, including players pets, tamed mobs, etc.

Or maybe /react act purge-entities not doing anything unless you specify after what you u want to purge

I think it'll be a really nice thing to add to the plugin

Thank you

**Comment by fyrmftw** [comment]
I've updated the plugin to latest, and /react act purge-entities doesn't purge my named mobs, but purges tamed and leashed. When I dont think there's even any purge rules in the config, only culling and I've got all 3 on Refuse.

**Comment by cyberpwnn** [comment]
I think purge entities should be used for purging everything. It's in the name. You shouldnt be using purge, instead use culling. That's the entire purpose of culling. To remove entities to reduce lag and NOT CAUSE MORE, purging just removes entities to spawn in new ones.

There is plenty of settings on the purge command however. The fastest way would be to  ctrl+f purge, however here are some
```yml
purge:

  # Allow the purger to purge named entities
  allow-purge-named: false

  # Allow the purger to purge item drops
  allow-purge-drops: false

  # Allow the purger to purge tamed entities
  allow-purge-tamed: false
```

And the purge list 
```yml
  allow-purging:
  - DROPPED_ITEM
  - AREA_EFFECT_CLOUD
  - ELDER_GUARDIAN
  - WITHER_SKELETON
  - STRAY
  - EGG
  - PAINTING
  - ARROW
  - SNOWBALL
  - FIREBALL
  - SMALL_FIREBALL
  - ENDER_PEARL
  - ENDER_SIGNAL
  - SPLASH_POTION
  - THROWN_EXP_BOTTLE
  - WITHER_SKULL
  - FALLING_BLOCK
  - FIREWORK
  - HUSK
  - SPECTRAL_ARROW
  - SHULKER_BULLET
  - DRAGON_FIREBALL
  - ZOMBIE_VILLAGER
  - SKELETON_HORSE
  - ZOMBIE_HORSE
  - ARMOR_STAND
  - DONKEY
  - MULE
  - EVOKER_FANGS
  - EVOKER
  - VEX
  - VINDICATOR
  - ILLUSIONER
  - MINECART_COMMAND
  - BOAT
  - MINECART
  - MINECART_CHEST
  - MINECART_FURNACE
  - MINECART_TNT
  - MINECART_HOPPER
  - MINECART_MOB_SPAWNER
  - CREEPER
  - SKELETON
  - SPIDER
  - GIANT
  - ZOMBIE
  - SLIME
  - GHAST
  - PIG_ZOMBIE
  - ENDERMAN
  - CAVE_SPIDER
  - SILVERFISH
  - BLAZE
  - MAGMA_CUBE
  - ENDER_DRAGON
  - WITHER
  - BAT
  - WITCH
  - ENDERMITE
  - GUARDIAN
  - SHULKER
  - PIG
  - SHEEP
  - COW
  - CHICKEN
  - SQUID
  - WOLF
  - MUSHROOM_COW
  - SNOWMAN
  - OCELOT
  - IRON_GOLEM
  - HORSE
  - RABBIT
  - POLAR_BEAR
  - LLAMA
  - LLAMA_SPIT
  - PARROT
  - VILLAGER
  - ENDER_CRYSTAL
  - FISHING_HOOK
  - TIPPED_ARROW
```

**Comment by fyrmftw** [comment]
Alright, i'll leave the purging since i'm only going to use it sometimes for certain things, everything else is amazing, thank you <3
