### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by p82183645** [VolmitSoftware/React#395]
![image](https://user-images.githubusercontent.com/5382252/41718977-2e81d4e4-7591-11e8-967b-5b851003a8bd.png)

very lag
He always appeared this, causing my server to severely lag

**Comment by lucas2107** [comment]
#398 & #399 reporting the problem is not fixed.

**Comment by cyberpwnn** [comment]
Your server doesnt support it then. Set spikes.report-spikes to false.

I cannot send this sync since you know... the server is kind of locked. So disable it. I'll find another way to display the information on unsupported server versions/flavors.

Assuming its only happening on paper/1.8?

**Comment by lucas2107** [comment]
Seems to be 1.12 paper

**Comment by p82183645** [comment]
spikes.report-spike  where?

What will happen to my closure?

**Comment by cyberpwnn** [comment]
In the config.yml
