### ISSUE TITLE
/re map ENTITY MS & TILE MS dont show up

### ISSUE THREAD

**Issue by wulfwuud** [VolmitSoftware/React#396]
Dump - http://paste.volmit.com/naxaqomibi.json
Core - git-Paper-ee2ec9fe (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
Viaver - 1.3.0
Plib - 4.3.0
Screenshots:
https://cdn.discordapp.com/attachments/267875254431514625/459337756699787284/unknown.png
https://cdn.discordapp.com/attachments/267875254431514625/459337851239268362/unknown.png

**Comment by lucas2107** [comment]
React Entities & Tiles entities monitoring seems to not be working on paper.

**Comment by cyberpwnn** [comment]
Thats because react doesnt support tile tick throttling. When react has the option to throttle, it also sneaks the tick time back to the sampler. Without the ability to inject the throttler there is no accurate way to get the time.

Ill see if there is a way to add support for paper11

**Comment by cyberpwnn** [comment]
There is no safe way to add support to this at the moment.
