### ISSUE TITLE
Entities culling name tag blocked

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#401]
The entities culling name tag isn't rly working on Paper 1.8.8
I set 200 ticks before despawn, so it's 10s, but sometimes name tag display 12.2s, etc...
I never saw the name tag going under 8.5s, idk why

Paper 1.8.8
React 6.561

**Comment by cyberpwnn** [comment]
Fixed in 6.565

**Comment by cyberpwnn** [comment]
![image](https://user-images.githubusercontent.com/10619135/41970498-1a466ca0-79d9-11e8-904a-da1bc54c626e.png)
