### ISSUE TITLE
Server lock messages with stacktrace are too long

### ISSUE THREAD

**Issue by creator3** [VolmitSoftware/React#403]
Staff are getting kicked because the length of some of the server lock messages is too long.

You might consider using the legacy color codes. They're significantly shorter.
The main downside is that the color resets to white when the line is wrapped.
However, hover texts don't wrap, so I'm not sure there's any reason not to use them.

**Comment by cyberpwnn** [comment]
I dont think using legacy color codes would help, i really just need to reduce the stack trace.

**Comment by cyberpwnn** [comment]
Fixed in 6.563
