### ISSUE TITLE
The issue of lag occurred again

### ISSUE THREAD

**Issue by p82183645** [VolmitSoftware/React#405]
![image](https://user-images.githubusercontent.com/5382252/41846670-034722ea-78aa-11e8-9dfb-2eeb2c0ee873.png)

paper 1.12.2

**Comment by cyberpwnn** [comment]
Did you not turn it off? Please turn off the feature, it isnt supported for your flavor of bukkit.

**Comment by cyberpwnn** [comment]
6.564 now ultimately ignores the setting and doesnt try anyways for paperspigot.
