### ISSUE TITLE
Color mismatch in monitor

### ISSUE THREAD

**Issue by i0xHeX** [VolmitSoftware/React#406]
There is a color mismatch in monitor at chunk section, where `chk_time` shows in **purple** color instead of **red**.
![image](https://user-images.githubusercontent.com/33582973/41847977-999bece2-7884-11e8-8aeb-aeb96e3afd1a.png)

**Comment by cyberpwnn** [comment]
I think its showing purple because its a physics timing value 
![image](https://user-images.githubusercontent.com/10619135/41881224-564943f0-78b0-11e8-96c1-e0cd5dbb9ac5.png)

**Comment by i0xHeX** [comment]
994^ ^ 0/s **(0ms)** | 9 - red (chunk time)
CHK: **0ms** (^ 0/s) | 5  - also chunk time?

**Comment by cyberpwnn** [comment]
You would be correct, and i'm blind.

**Comment by EthanTG** [comment]
of course you are :)

**Comment by cyberpwnn** [comment]
Ill add color support later. The formatters are cached to save memory which is why changing it would screw up the default monitor.
