### ISSUE TITLE
Force culling limits option

### ISSUE THREAD

**Issue by cyberpwnn** [VolmitSoftware/React#408]
Add an option to force culling limits

**Comment by Frerduro** [comment]
ew

**Comment by cyberpwnn** [comment]
Added in 6.565

Turns out its very efficient and is faster at culling cows than how long it takes them to fall from the sky on spawn
![image](https://user-images.githubusercontent.com/10619135/41970078-7bffefae-79d7-11e8-84ad-ea97d9780250.png)
