### ISSUE TITLE
Cobsole Error

### ISSUE THREAD

**Issue by Clasher31HD** [VolmitSoftware/React#413]
When i want to reload my server then i receive this ERROR:
https://pastebin.com/F7cQX5Tr

Pls fix it

**Comment by Frerduro** [comment]
Did you use /re reload or /reload?

**Comment by Clasher31HD** [comment]
I used /reload

**Comment by Clasher31HD** [comment]
Spigot 1.8.8

**Comment by cyberpwnn** [comment]
Never use reload. especially with protocol hacks. React can only safe-disconnect from protocollib when using /re reload.

**Comment by cyberpwnn** [comment]
However with that said, the error you are seeing is basically react just failing to use protocollib (because protocollib was broken upon reload)

So react should still function fine (except for /re ping) 

Im closing this issue for now.
