### ISSUE TITLE
[Bug] Exception in React Monitor

### ISSUE THREAD

**Issue by TheWranger** [VolmitSoftware/React#416]
28.06 02:40:17 [Server] INFO [React] Enabling React v6.565
28.06 02:40:18 [Server] WARN Exception in thread "React Monitor" java.lang.NullPointerException
28.06 02:40:18 [Server] WARN at com.volmit.react.util.TPSMonitor.run(TPSMonitor.java:75)
28.06 02:40:18 [Server] INFO React: Language: enUS

Error on server startup
Paperspigot 1.12.2

**Comment by EthanTG** [comment]
#414

**Comment by cyberpwnn** [comment]
#415
