### ISSUE TITLE
Stack mob type Cave_Spider is not working

### ISSUE THREAD

**Issue by WindUnwaken** [VolmitSoftware/React#419]
Stack mob in each type of mob works well, but not Cave_Spider

**Comment by cyberpwnn** [comment]
Are there any exceptions? Send your allow-stacking list

**Comment by WindUnwaken** [comment]
https://pastebin.com/ZZbf4pBX

**Comment by cyberpwnn** [comment]
Cant seem to reproduce it.

**Comment by SwiftSwamp** [comment]
Closing as this was likely fixed in the latest updates... and the issue is old. Please reopen if the issue continues.
