### ISSUE TITLE
Time Selector not working

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#422]
![command](https://user-images.githubusercontent.com/34198310/42130290-a3794382-7cb6-11e8-835c-edca642a1465.png)

React 6.567
PaperSpigot 1.10.2
Dump: http://paste.volmit.com/vagicegoyu.json

**Comment by lucas2107** [comment]
Seems happening on Paper only. Same bug on 1.8.8 Paper

**Comment by cyberpwnn** [comment]
1 hour is a very long time. Mostly because when chunks unload and re-load again they will unlock.

**Comment by cyberpwnn** [comment]
Uncapped max time from 10 seconds to infinity in 6.568

**Comment by lucas2107** [comment]
1 second wasn't working too @cyberpwnn

**Comment by cyberpwnn** [comment]
I just tested it, the time selector works exactly how it is supposed to.
