### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Clasher31HD** [VolmitSoftware/React#424]
On start:
https://pastebin.com/SePCSbBj

**Comment by lucas2107** [comment]
Server version?

**Comment by cyberpwnn** [comment]
Were you reloading it? does this happen on normal server startup?

**Comment by Clasher31HD** [comment]
I reloaded the server, but ...
What is bad on reloading? I love reloading, it is fast, easy and usefull! It's arduous to stop the server and start it again! Why you can't fix this error that i can reload it correctly?

**Comment by cyberpwnn** [comment]
Get biletools or plugman. Reloading leaks memory and doesnt clean up properly causing tons of issues.
