### ISSUE TITLE
Fast leaf decay enhancement

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/React#426]
Its very difficult for our builders to construct giant tree builds with fast leaf decay. Could you add a feature where being in creative doesn't trigger fast leaf decay. Additionally, shift left click to not trigger leaf decay could also be a viable option (Though the creative option would be better as this would make building the trees a bit more difficult while flying).

**Comment by cyberpwnn** [comment]
Creative places leaves blocks with a flag on it to NOT decay. React follows this.

However something like WorldEdit or FAWE does not unless you flag it yourself. Anything that would normally decay (because it isnt flagged) is fast-decayed by react if updated.
