### ISSUE TITLE
Periodically kicks player with Internal Error

### ISSUE THREAD

**Issue by i0xHeX** [VolmitSoftware/React#431]
When you have map monitor enabled or that map on the wall, then sometimes it kicking with Internal Error: https://privatebin.net/?d7b169568b6b1555#hH8ayn3WekHSqvJCcx3AznMmbq6lU5PYJcWAoeZ0os8=
Issue detected using React 6.568
No such issues were detected on React 6.558

**Comment by i0xHeX** [comment]
Not bungeecord, just simple test server

**Comment by SwiftSwamp** [comment]
Closing as this was likely fixed in the latest updates... and the issue is old. Please reopen if the issue continues.
