### ISSUE TITLE
/re ping doesnt work on 1.13

### ISSUE THREAD

**Issue by RiftBladeMc** [VolmitSoftware/React#444]
![2018-07-27_21 41 18](https://user-images.githubusercontent.com/41810843/43352230-21470bd4-91e6-11e8-8493-e10cff5e0b76.png)
Version: Paperspigot-49/ React 6.572

**Comment by cyberpwnn** [comment]
It's working on Spigot 1.13 after a second or two. It only calculates the ping when the server sends KEEP_ALIVE which on 1.12+ is slow... like every 10 seconds or so.

**Comment by Frerduro** [comment]
works for me on spigot and paperspigot

**Comment by LogGits** [comment]
Works for me aswell

**Comment by cyberpwnn** [comment]
I have two confirmations that it works. Closing for now. I'll have some testing done on it. Perhaps its the protocollib version or something happened during startup which prevented the packet listener from spinning up?
