### ISSUE TITLE
Combine mobs only from spawners

### ISSUE THREAD

**Issue by blazex224** [VolmitSoftware/React#446]
Hey, my apologies if this is already a feature, but I was wondering if there was a way to combine mobs, but only if the mobs are spawned from a mob spawner. Thanks for the plugin!

**Comment by cyberpwnn** [comment]
Its under stack reasons. Just remove reasons to stack from the list that you dont want,
![image](https://user-images.githubusercontent.com/10619135/43856685-3b7a83a2-9b17-11e8-83e0-7d985b2db800.png)
