### ISSUE TITLE
New /re act - Lock Plant Growth

### ISSUE THREAD

**Issue by HexedHero** [VolmitSoftware/React#448]
Having the plant growth lock will be good because when players are using auto melon farms and other stuff when Redstone is locked, the melon grows and it doesn't fire the Redstone thus making that bit of the farm useless until you come along and fix it!

Also would just be a nice addition to React to stop lag with auto farms such as bone meal spammers etc!

**Comment by GhostedThoughts** [comment]
This would be an absolutely amazing feature, for things like auto farms, this would prevent so many lockups, potentially saving people plenty of hours of troubleshooting, I know a good handful of people who'd love this!

**Comment by MrMeeks** [comment]
Yes, This would be great.  Great suggestion!

**Comment by cyberpwnn** [comment]
Use /re act throttle-physics
