### ISSUE TITLE
Word mistake

### ISSUE THREAD

**Issue by Darko266** [VolmitSoftware/React#450]
SORRY that i didn't find them earlier :disappointed: 

![mistake](https://user-images.githubusercontent.com/20874142/43859531-2f6c92aa-9b51-11e8-9a15-162329f3ff63.jpg)
![mistake_2](https://user-images.githubusercontent.com/20874142/43859532-2f8c35ec-9b51-11e8-8a74-9ea0c577d244.jpg)

This is in placeholders.txt
![33](https://user-images.githubusercontent.com/20874142/43859924-5b2450e4-9b52-11e8-9831-388b7c21fd7c.jpg)

**Comment by NextdoorPsycho** [comment]
Fixing that right now! @Darko266  thanks for the report
