### ISSUE TITLE
Low TPS with new React

### ISSUE THREAD

**Issue by fyrmftw** [VolmitSoftware/React#453]
Hello,

I've recently switched over to the new react and using it on a 1.12.2 server,
and after configuring it and adding it on our server, i've noticed very high TPS spikes, where the tps
would drop from 20, to 2, then fluctuate between 2-10, then go back up to 20 again. It would drop like every 30 seconds/1m.

TPS is dropping and fluctuating a lot and I dont know if im using the wrong version or something since it said the build was a pre built 1.13 version of react and that it was going into 1.13 safemode.

But heres the timings reports that I got
https://timings.spigotmc.org/?url=dijinidafa
https://timings.spigotmc.org/?url=yunovokixi

Which version do you recommend me using for 1.12.2

**Comment by NextdoorPsycho** [comment]
hmmm not the first ill take a look into this :)

**Comment by fyrmftw** [comment]
Thank you!

**Comment by SwiftSwamp** [comment]
Hello, is this still an issue?
