### ISSUE TITLE
/re Installagent 100% will not work

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#455]
All it will say is that it's "Downloading Volume Memory Agent."
"Download FAILED!"

I have never seen it work, I'm still so interested xD
React 6.574
Spigot 1.13.1

It fails to download classmexer.jar, no matter what I do

**Comment by CaptainAmpersand** [comment]
There is no error inside console, either.

**Comment by Frerduro** [comment]
This is not a 1.13 bug

**Comment by DavidRockin** [comment]
Download location for the library's jar was moved on the repository. It has been fixed in e9bce9e3ca7c32a195f5f3ce7a6c8fe630ef1962, and will be released in 6.612. Thanks for the issue report.
