### ISSUE TITLE
Startup errors on 1.13.1

### ISSUE THREAD

**Issue by Sikatsu** [VolmitSoftware/React#457]
On every startup I receive this error in the console: https://pastebin.com/zfhijK8a
It also seems React has to restart after a server restart:

15.09 16:02:48 [Server] INFO React Supersampler has crashed. Reloading React.
15.09 16:02:48 [Server] INFO SS has not responded for over -1ms

**Comment by cyberpwnn** [comment]
Please watch https://github.com/VolmitSoftware/React/pull/465
