### ISSUE TITLE
[ISSUE] Permission to monitor and scoreboard without environment

### ISSUE THREAD

**Issue by FaMa91** [VolmitSoftware/React#462]
We would like to give to some trusted players of the staff the access to Monitor and Scoreboard : right now we grant them these permissions:
- react.access
- react.monitor.title
- react.monitor.actionlog

But this way they have access to other commands like Environment, we don't think is actually possible to grant permission to only these commands.

We are using 6.541 and can't update right now, but if we run "/re scoreboard" command to hide the scoreboard we get always kicked from server, is this bug already fixed?

Thank you in advance!

**Comment by Frerduro** [comment]
Please update react to see if your problem is fixed

**Comment by FaMa91** [comment]
Talking about the kick on scoreboard closing, I'm on 6.581 version and the bug still persist. I think the bug it's related to BungeeCord because on a different server I don't have this issue.

When I get kicked I have this message from BungeeCord:
The server you were previously on went down, you have been connected to a fallback server

The fallback server is the Hub server in my case.

Thank you in advance, I'll try to pay attention to this issue and reply quickly.

**Comment by relavis** [comment]
Likely fixed with new scoreboard changes.
