### ISSUE TITLE
react api

### ISSUE THREAD

**Issue by mechoriet** [VolmitSoftware/React#463]
Hello,

how would i get these values
![image](https://user-images.githubusercontent.com/4313219/51803066-dfdc5e00-2250-11e9-92ed-d68fa7cf150e.png)
in my own plugin to send to our monitoring (grafana) the ms value?
since there is no api guide or i missed it.

Thanks in advance

**Comment by cyberpwnn** [comment]
```java
// Sampler for CPU Usage
ISampler s = React.instance.sampleController.getSampler(SampledType.CPU.toString());
s.getValue() //raw value
s.get() // formatted string value
```

All sampled types are in enum SampledType
