### ISSUE TITLE
Make React Console-Friendly

### ISSUE THREAD

**Issue by Drc-DEV** [VolmitSoftware/React#475]
Most of the commands cannot be executed by console for monitoring, it would be cool to have some sort of console monitoring of the server.

**Comment by cyberpwnn** [comment]
the /react command will now only show console capable commands while in the console

**Comment by cyberpwnn** [comment]
Added /re mon for console support (prints out the monitor)

**Comment by cyberpwnn** [comment]
Actions are now listed when using /re act

**Comment by Drc-DEV** [comment]
Thank you for the recent update! Adding more functionality from console is a real time-saver for me.

**Comment by cyberpwnn** [comment]
:P thats why i havent closed it
