### ISSUE TITLE
Add /re scoreboard support for 1.13.2

### ISSUE THREAD

**Issue by i0xHeX** [VolmitSoftware/React#479]
React 6.594
This is related to closed issue: https://github.com/VolmitSoftware/React/issues/456

But the issue is not solved, we still don't have scoreboard support for 1.13.2.
On `/re scoreboard` is says: `Scoreboards (requires 1.5-1.12.2)`

**Comment by cyberpwnn** [comment]
Yeah, no, thanks for bringing this back up. Ill have it implemented eventually. Just got mapping working.

**Comment by cyberpwnn** [comment]
![image](https://user-images.githubusercontent.com/10619135/52484604-bee70780-2b84-11e9-8232-f6e7aef98a18.png)
