### ISSUE TITLE
React monitor error

### ISSUE THREAD

**Issue by Sikatsu** [VolmitSoftware/React#485]
Error when using the monitor: https://pastebin.com/ZVrkmJiW

**Comment by cyberpwnn** [comment]
Missing information.

Use -XX:-OmitStackTraceInFastThrow in your launch args.

**Comment by Sikatsu** [comment]
I'm not on a dedicated server. How do I do this?

Op za 16 feb. 2019 01:58 schreef Dan <notifications@github.com:

**Comment by cyberpwnn** [comment]
Just the jvm start flags. If you cant get that info, i cant possibly know where the problem is coming from.

**Comment by Sikatsu** [comment]
I haven't seen this error anymore.

**Comment by cyberpwnn** [comment]
Alright, ill close it for now then
