### ISSUE TITLE
React wont work on Spigot 1.13.2

### ISSUE THREAD

**Issue by YourPalJake** [VolmitSoftware/React#490]
Hi there,

I used the build script to try out the plugin and see if it was worth buying and useful for my case. Although on start I immediately got an error. So here it is.

Error Log: https://pastebin.com/UJZSuPeJ

**Comment by UnoriginalName** [comment]
20.03 13:07:52 [Server] WARN Caused by: java.util.MissingResourceException: Can't find bundle for base name com.volmit.react.lang, locale en_US

**Comment by DavidRockin** [comment]
Issue with how languages are bundled. I've resolved it in 9eab2ca76ab9f61419c45246b8b9e7b318dfaca2

This issue only affected manually building the jar yourself and not the downloadable production jar off Spigot.
