### ISSUE TITLE
High cpu usage on 1.8 servers

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#492]
Since 20-40 versions from now, React is using a lot of CPU for a task (interval: 1t).

React v6.609 Total: 26.82 s Pct: 54.48%

   Pct Total    Pct Tick       Total          Avg     PerTick         Count        Event

      53.32%      69.44%     26.25 s        34.72 ms     2.0           1.5k        Task: Task$2(interval 1)

**Comment by cyberpwnn** [comment]
Hmmm that is a lot. How long was it sampling for?

**Comment by lucas2107** [comment]
This is happening all time. I had a timings for 10 minutes, same problem.

**Comment by DavidRockin** [comment]
Hi, if you are still experiencing this issue, can you do a complete timings report from server startup (enable plugin profiling in bukkit.yml) and include it here. You can also send it to me (Dave#0001) on the Discord server. Cheers.

**Comment by lucas2107** [comment]
Hey, I can't do it again :/ My server isn't on 1.8.8 now x)
