### ISSUE TITLE
Chunk Relighting not compatible with 1.13

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#493]
Could be because FAWE is aids in 1.13, could be just an issue that fell through the cracks.
React 6.61
Spigot 1.13.2

/re a fix-lighting with FAWE installed says, "x Chunk Relighting (requires UNKNOWN - 1.12.2)"

**Comment by DavidRockin** [comment]
React and Primal did not support 1.13.x+ but the new 6.612 should support it now
