### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Diaxower** [VolmitSoftware/React#495]
Console error while used monitor
https://paste.md-5.net/piwijevide.cs

**Comment by Frerduro** [comment]
Spigot version please.

**Comment by Diaxower** [comment]
PaperSpigot-1.8.8-R0.1

pon., 15 kwi 2019 o 02:09 Frerduro <notifications@github.com> napisał(a):

**Comment by DavidRockin** [comment]
Hi, thanks for reporting this issue. There was a minor issue when it came to defaulting on the monitor selection, this has been fixed and will be released in 6.612
