### ISSUE TITLE
Disabling take ages [1.8]

### ISSUE THREAD

**Issue by UnioDex** [VolmitSoftware/React#496]
Version: 6.61
Server Version: Custom Fork of TacoSpigot 1.8.8

When i stop the server message "Disabling React 6.61" comes and server is not stopping for 10 minutes. I don't know what is happening at disabling but that's not normal and started to happen with latest updates.

**Comment by SwiftSwamp** [comment]
Hello,

Could you please provide your latest.log so I can take a look.

**Comment by cyberpwnn** [comment]
I dont see anything that would cause a deadlock or any lock of the sort. However, it could be the SuperSampler shutting down, but failing to interrupt itself.

**Comment by UnioDex** [comment]
Sorry but because of this problem I removed React and of course my logs long ago. So I can't provide any logs.
