### ISSUE TITLE
1.14.3 Chunk Purging's wonky or off

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#503]
Server version 1.14.3 paper 127
React version 6.612
There are 4 players online. On 1.13/1.12, there would be only a few hundred chunks per player, right now, it is up to 5,474 chunks. That's 1,368.5 chunks per player. I don't think that's right.

**Comment by CaptainAmpersand** [comment]
In addition, when doing /re a pc, it doesn't appear to purge... Any. It will purge one chunk. Not really.. Gonna work.

**Comment by DavidRockin** [comment]
1.14 has a lot of issues with chunks. I did notice a lot of chunks were loaded on a vanilla SMP server (minimal plugins, no players on). I'm curious if it relates to render distance, perhaps an internal bug not properly unloading a chunk if a player leaves a chunk?

**Comment by DavidRockin** [comment]
Indeed it's an issue related to Minecraft:
https://github.com/PaperMC/Paper/issues/2106

Forcing a chunk to unload (`Chunk.unload()`) has virtually no response.

**Comment by DavidRockin** [comment]
In 1.14, the minimum number of chunks open (for render distance) has been altered. Although there appears to be an issue with 1.14 where chunks do not unload properly. Chunks might be fixed in [1.14.4 Pre-release 2](https://minecraft.gamepedia.com/Java_Edition_1.14.4_Pre-Release_2)

**Comment by CaptainAmpersand** [comment]
That's definitely a possibility, however, it seems as though React adds fuel to that fire.

It's trying to purge them, but unsuccessfully. Minecraft without React seems to properly purge them over time, at least, doesn't seem to report as many being active.

**Comment by CaptainAmpersand** [comment]
The fixed implemented in 6.613-dev definitely help. Currently running at a relatively stable rate with 20 players online

**Comment by DavidRockin** [comment]
👍 How many chunks, tiles and entities, and what is average TPS?

**Comment by CaptainAmpersand** [comment]
With 20 players, 7.5k chunks (Render Distance of 8)
Average TPS of ~13 (5 minutes)
2.2k Entities average. Culling them clears about 100 each time

Timings: https://timings.aikar.co/?id=02fe079e7de34156b13ba2377b8ec1d0
