### ISSUE TITLE
Excessive tick usage/lag on React-v6.610 Paperclip-1.8.8

### ISSUE THREAD

**Issue by Benlewis9000** [VolmitSoftware/React#505]
React v6.610 has been using causing large TPS drops and consistent lag, as is shown with /re mon and numerous timings reports, e.g. 
https://timings.aikar.co/?id=c45833629cf64b589d6f4277320eb193#plugins

I am not using v6.611 as it performed even worse.

My plugins can be found at:
https://gyazo.com/21ef98d67bdc9a4092fb4fbd72c0d71b

**Comment by DavidRockin** [comment]
Please upload your config

**Comment by lucas2107** [comment]
Duplicated #492

**Comment by Benlewis9000** [comment]
https://pastebin.com/F6u6Kpdk

**Comment by DavidRockin** [comment]
@Benlewis9000 could you disable mob spawning temporarily and see if this issue persists? As well please take another timings report.
