### ISSUE TITLE
React ping, too slow

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#506]
Hey,

React is taking a very long time to refresh the players ping ( 25s ).

Could you add a config for that?
![react ping](https://user-images.githubusercontent.com/11612016/61094766-d175ad80-a450-11e9-9ad2-3841dfcb7fe2.png)

**Comment by DavidRockin** [comment]
React's pings listens for player's keepalive packets. The duration of these packets are hard coded in the server and client side. PaperSpigot DOES have an option to increase the keep alive timeout, but that would not resolve your option. I guess theoretically you could manually send these packets, but I don't think that would be very wise to mess around with player timeouts.
