### ISSUE TITLE
Fact leaf decay doesn't work

### ISSUE THREAD

**Issue by BobbyMere** [VolmitSoftware/React#511]
**Describe the bug**
After setting every section under "fast-leaf-decay" to true, leaves still decay like vanilla after breaking all connecting wood logs, and having no other wood logs connected to the tree (all wood logs are gone).

**To Reproduce**
1. Go to a tree
2. break all wood logs
3.tree decays like
4. see no error in console

**Expected behavior**
All the leaves would instantly be decayed like It was when I was on 1.12.2

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Informations**
 - Installed plugins: Plugins (8): CoreProtect, Essentials, FastAsyncVoxelSniper, FastAsyncWorldEdit, Multiverse-Core, React*, WorldEdit, WorldGuard
 - React Version: 6.610
 - Server Platform and Version paper 1.13.2
 - Operating System (if applicable):

**Additional context**
This happens on both my production server and my test server. However, this problem didn't exist until I moved to 1.13.2

Every game rule and plugin I use on the server while testing this, besides react, was default

My config: https://pastebin.com/8d1E3tPZ
------------------------------------------------
**updated**
I tested the exact same set in paper 1.12.2 and it worked exactly as I remember it working. All the leaves instantly (almost instantly) decayed. The issue is 1.13.2

**Comment by relavis** [comment]
Will be fixed in 6.649.
