### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OverBrave** [VolmitSoftware/React#519]
![image](https://user-images.githubusercontent.com/47111280/64937293-68e8e980-d862-11e9-94c0-17b8eaee5e72.png)

**Server and Plugin Informations**
 - Installed plugins: 
![image](https://user-images.githubusercontent.com/47111280/64937284-61294500-d862-11e9-911d-5642237abd89.png)

 - React Version: 6.614
 - Server Platform and Version PaperSpigot 1.14.4
 - Operating System (if applicable): Windows VDS

**Comment by relavis** [comment]
Doesn't appear to be an issue anymore
