### ISSUE TITLE
Link to download classmexer-1.0.jar is down

### ISSUE THREAD

**Issue by Kira07** [VolmitSoftware/React#522]
**Describe the bug**
The command "react installagent" returns "Download failed" because the download URL is down (http://nexus.volmit.com/content/repositories/thirdparty/com/javamex/classmexer/1.0/classmexer-1.0.jar)

**To Reproduce**
Type "react installagent"

**Expected behavior**
A successful download.

**Comment by DavidRockin** [comment]
Duplicate of #517
