### ISSUE TITLE
Player roll back when they are quit and join

### ISSUE THREAD

**Issue by CruelReality** [VolmitSoftware/React#523]
![react](https://user-images.githubusercontent.com/33629291/66731774-9178f900-ee8b-11e9-9200-a80d89a41272.png)

When this error occurs,someone will be roll back when they are quit and join.Restart server can solve this problem.This error occurs every day.Then i uninstall react.This error hasn't happened for a week.

 - React Version: 6.614
 - Server Platform and Version: PaperSpigot-196 1.14.4

**Comment by relavis** [comment]
Should be fixed, please try latest versions.
