### ISSUE TITLE
PaperMC 1.14.4 ERROR

### ISSUE THREAD

**Issue by a0979273859** [VolmitSoftware/React#526]
After entering /react book, it won't display

https://cdn.discordapp.com/attachments/289587909051416579/663747652189683712/b9c86840bbf9628b.PNG

**Comment by relavis** [comment]
Fixed with https://github.com/VolmitSoftware/React/pull/545/commits/3489b580915705547ef372451f298a468d6610e6

**Comment by relavis** [comment]
PR #545 has been merged.

Please let us know if you have any other issues :)
