### ISSUE TITLE
Could not pass event PlayerLoginEvent

### ISSUE THREAD

**Issue by Ant4rez** [VolmitSoftware/React#527]
**Describe the bug**
When a player joins to the server React throughs an error.

**To Reproduce**
1. Join the server.

**Expected behavior**
Join to the server and see no errors on console.

**Server and Plugin Informations**
 - Installed plugins: AuthMe, BossShopPro, CoreProtect, DeluxeCombat, Essentials, EssentialsChat, EssentialsSpawn, ezAuctions, FastLogin, GemsEconomy*, IllegalStack, JupiterCore, LuckPerms, Matrix, mcMMO, Minepacks, MoneyHunters, MysqlEconomyBank, OpGuard*, PlaceholderAPI, PlayerShops, ProtectionStones, ProtocolLib, React*, SkinsRestorer, TitleManager*, UltimateCatcher, UltimateStacker, Vault, ViaVersion*, WorldBorder, WorldEdit, WorldGuard, Zenchantments

 - React Version: v6.614

 - Server Platform and Version: Paper version git-Paper-238 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Additional context**

https://paste.ubuntu.com/p/7QghDcWy65/

https://paste.ubuntu.com/p/zn6VhZT8qm/

**Comment by relavis** [comment]
Should be fixed, please try latest versions.
