### ISSUE TITLE
Warning "No NMS Binder Found i cricket 1.14" in Paper 1.15.1

### ISSUE THREAD

**Issue by In77** [VolmitSoftware/React#528]
**Describe the bug**
While server starting, react will report
"No NMS Binder Found i cricket 1.14"
then print warning
"java.lang.NoClassDefFoundError"

May not affect plugin functions? (not tested)

**Screenshots or Video Recordings**
<img width="787" alt="Screenshot 2020-01-13 at 21 52 47" src="https://user-images.githubusercontent.com/44344308/72261299-829f0f80-364f-11ea-90f2-fb902a02f015.png">

**Server and Plugin Informations**
Windows Server 2019 x64
Paper 1.15.1 Build 46
React 6.615

**Comment by In77** [comment]
<img width="749" alt="Screenshot 2020-01-13 at 22 12 55" src="https://user-images.githubusercontent.com/44344308/72262447-e62a3c80-3651-11ea-8c35-85a9fdcf83a7.png">
NCDFE for 1.14 packet

**Comment by In77** [comment]
<img width="749" alt="Screenshot 2020-01-13 at 22 12 55" src="https://user-images.githubusercontent.com/44344308/72262517-0fe36380-3652-11ea-873e-ecf7fb05f982.png">
Still warning for NoClassDefFoundError

**Comment by cyberpwnn** [comment]
Much fun...

**Comment by cyberpwnn** [comment]
Alright I actually fixed it this time. Check spigot

**Comment by In77** [comment]
<img width="434" alt="Screenshot 2020-01-13 at 22 26 28" src="https://user-images.githubusercontent.com/44344308/72263459-dd3a6a80-3653-11ea-97ec-4806ba9cc9f2.png">
OK

**Comment by cyberpwnn** [comment]
WOOOOOOOO Finally i can sleep :P
