### ISSUE TITLE
Add web-based version of ReactClient

### ISSUE THREAD

**Issue by Andre601** [VolmitSoftware/React#529]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be a nice feature, to have a web-version of the ReactClient, to monitor and perhaps display stats of your server on a website.
I always wanted to display to players how powerful the server is, but I lack a proper system to do so.

That way could you have something like mysite.com/react and it would display a page containing various information like current TPS, RAM usage, etc. (Pretty much everything that can be shown through the react map)

**Describe alternatives you've considered**
The ReactClient is really the only alternative but not that useful for what I imagine.

**Additional context**

**Comment by TheAgentRAINBOW** [comment]
I second this
