### ISSUE TITLE
React commands don't work with Paper 1.15.2 Build 134 and higher

### ISSUE THREAD

**Issue by In77** [VolmitSoftware/React#535]
**Describe the bug**
React doesn't work with Paper 1.15.2 Build 134 and higher
but it works with Build 133

**To Reproduce**
Tested with paper build 133, 134, 135

**Screenshots or Video Recordings**
<img width="950" alt="Screenshot 2020-03-15 at 08 25 09" src="https://user-images.githubusercontent.com/44344308/76692869-a60a2900-6697-11ea-82d5-08cbe2a27475.png">

**Server and Plugin Informations**
 - React Version: 6.617
 - Server Platform and Version: Paper 1.15.2 Build 135
 - Operating System: Windows Server 2019

**Comment by In77** [comment]
react 6.618 works with Paper now, but it reports error on disabling.
<img width="869" alt="Screenshot 2020-03-20 at 09 36 36" src="https://user-images.githubusercontent.com/44344308/77129711-f1ee1100-6a8f-11ea-95bd-1bfeca0d01f7.png">
this error probably not affect plugin function.

**Comment by NextdoorPsycho** [comment]
just want to say that MOST plugins need a whole rework to support 1.15+ but react will actually support it soon

**Comment by relavis** [comment]
If experiencing this error, please use the latest version of Paper 1.15.2. Paper 378 confirmed to be working.

**Comment by relavis** [comment]
I apologize, it appears that this is still an issue. React loads but all commands are broken.

**Comment by cyberpwnn** [comment]
Theory: Paper broke something we are using
Question: Does AsyncChatEvent still fire? (try using `/mem`). If that works.......
Idea: Comparability mode which shoves all command registries into an AsyncChatEvent listener for paper 1.15

**Comment by relavis** [comment]
Fixed
