### ISSUE TITLE
React with ProtocolLib in combination with WitherAntiCheat causes "Timed out kicks" due to KeepAlive

### ISSUE THREAD

**Issue by BluLightShow** [VolmitSoftware/React#537]
**Describe the bug**
With WitherAntiCheat, React, and ProtocolLib on the server, all players are kicked after some time with different network-related errors, the most common one being "Timed out"

**To Reproduce**
1. Install WitherAntiCheat ([GitHub](https://github.com/Olexorus/WitherAC), [SpigotMC](https://www.spigotmc.org/resources/wither-anti-cheat-1-13-x-1-15-x-paper-tuinity-support-free-accurate-optimized-anti-cheat.68657/)). Leave default configurations for everything.
2. Start server
3. Connect and continue to move around.
4. You will be kicked after some time with an error in console `Playername was kicked due to keepalive timeout!`

**Expected behavior**
The server doesn't kick you for playing.

**Screenshots or Video Recordings**
N/A

**Server and Plugin Informations**
 - Installed plugins: WitherAntiCheat and ProtocolLib
 - React Version: 6.618
 - Server Platform and Version [eg: PaperSpigot 1.15.2]:
 - Operating System (if applicable): Linux 4.15.0-47-generic (amd64) with Java 1.8

**Additional context**
N/A

**Comment by relavis** [comment]
Confirmed still a problem on latest React and WAC

**Comment by cyberpwnn** [comment]
Try disabling `features.react.monitor.fast-ping`

**Comment by relavis** [comment]
Disabling `features.react.monitor.fast-ping` solves this problem.
