### ISSUE TITLE
Legacy plugin React v6.618 does not specify an api-version

### ISSUE THREAD

**Issue by LukeBouch** [VolmitSoftware/React#543]
Any idea why I am getting this warning.

Server Host: SkyNode.Pro
Jar: Paper-1.15.2

>.... [00:46:03 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
>.... [00:46:07 WARN]: Legacy plugin React v6.618 does not specify an api-version

**Comment by relavis** [comment]
Hello,

This is normal to allow for support for multiple versions of MC. You can ignore these messages. They won't affect the functionality of the plugin.

**Comment by deRaidA** [comment]
Is there a way to specify the api version of the plugin on the own server?
_It's just to tidy up the console a bit._
