### ISSUE TITLE
"/re act" icons not labeled correctly

### ISSUE THREAD

**Issue by relavis** [VolmitSoftware/React#548]
**Describe the bug**
`/re act`'s icons do not have correct names or lore.

**To Reproduce**
It's unclear why this issue is occurring for this user. Their steps:
1. Drag and drop React into plugins folder
2. Open `/re act`
3. See unnamed icons

**Expected behavior**
Icons in `/re act` should be named to match their action and show lore.

**Screenshots or Video Recordings**
![Screenshot of `/re act`](https://media.foxedin.xyz/ss/javaw_GZa3dvre4K.png)

**Server and Plugin Informations**
 - Installed plugins:
![Plugins list](https://cdn.discordapp.com/attachments/189665083817852928/733075765528363068/unknown.png)
 - React Version: 6.630
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: Paper 90 (1.16.1)
![/version output](https://cdn.discordapp.com/attachments/189665083817852928/733075639778934794/unknown.png)
 - Operating System (if applicable): Linux
![/re env output](https://cdn.discordapp.com/attachments/710705306229014579/733087765134311585/unknown.png)
**Additional context**
Add any other context about the problem here, server timings reports, React dump information, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by cyberpwnn** [comment]
Hello hashtables my old friend......

I'm probably iterating over a keyset from a hashmap and it's screwing things up. Also the hashcodes may not be proper.

**Comment by relavis** [comment]
Fixed a long time ago in a galaxy far, far away
