### ISSUE TITLE
chicken egg

### ISSUE THREAD

**Issue by Bricec6** [VolmitSoftware/React#552]
**Describe the bug
The chicken stacker does not take into account the number of chicken, if we have 13 chicken stack we will only get one egg.

video: https://youtu.be/BR0bf2jb0-M

**Expected behaviour**
If we stack chickens we would need more eggs, for example 13 chickens would give us 7 eggs, or randomly between 0 and 13 eggs.

**Server and plugin information** **Information about the server and plug-ins
 - Reaction version: React 6.632
 - Platform and server version: paper-375 1.15.2
 - Operating system (if applicable): window(or debian)

**Comment by cyberpwnn** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/10619135/87853009-c14ea480-c8d4-11ea-9f33-60d6a41bebbd.png)
