### ISSUE TITLE
sheep color bug

### ISSUE THREAD

**Issue by Bricec6** [VolmitSoftware/React#554]
**Describe the bug
Hello there's a bug with the sheep, it's not dropping the right colour of wool.

Video: 
https://www.youtube.com/watch?v=yZnyfN3QNG8

**Server and Plugin Information **
 - Reaction version: React 6.632
 - Platform and server version: paper-375 1.15.2
 - Operating system (if applicable): window(or debian)

**Comment by cyberpwnn** [comment]
Fixed for 1.13-1.16
