### ISSUE TITLE
sheep stack per color

### ISSUE THREAD

**Issue by Bricec6** [VolmitSoftware/React#555]
**Is there a problem with your request for a report? Please describe it.
Hello is it possible to make stacking conditions between sheep colors?
For example, brown sheep stack with brown, red with red...

**Describe the alternatives you have considered**
In the allow-stacking configuration:
BLUE_SHEEP: 13
YELLOW_SHEEP: 13
RED_SHEEP: 14

or: 
sheep-stack-per-color:
enable: true
BLUE_SHEEP: 13
YELLOW_SHEEP: 13
RED_SHEEP: 14

 allow-stacking:
  - SHEEP

**Server and Plugin Information **
 - Reaction version: React 6.632
 - Platform and server version: paper-375 1.15.2
 - Operating system (if applicable): window(or debian)

**Comment by cyberpwnn** [comment]
Added the config option 
```yml
# Only stack sheep with the same color
sheep-color-specific: false
```

Under entity-stacker options.

It's defaulted to off, so when the update comes out you will need to turn it on.
