### ISSUE TITLE
2 Bugs, (Cause Huge TPS Drops)

### ISSUE THREAD

**Issue by AZFire1** [VolmitSoftware/React#557]
**Describe the bug**
The first bug has to do with the Mob Stacker, it stacks mobs but when you kill them manually it has no drops. Though, if they die like any other mob would it does drop what it's supposed to drop.
The second bug has to do with Insta-Breaking blocks and a lot of them at once like Sugar-Cane or Mining Dirt with a High Efficiency Shovel. If you do it enough, the TPS often would drop to 0 - 4 and spike until it suddenly goes back up to 20 as if nothing had happened.

**To Reproduce**
(Bug 1 Insta Break):
  * Just make yourself a decent sized sugar cane farm
  * Start breaking and watch the TPS drop before your eyes.
(Bug 2 Mob not Dropping Drops on manual death):
  * Stack a bunch of mobs
  * Start killing them with a sword and nothing will drop.

**Expected behavior**
(Bug 1 Insta-Break): I expect for the TPS to suffer until it somehow goes back up to 20 as if nothing had happened
(Bug 2 Mob not Dropping Drops on manual death): I expect there to be no drops on the manual kill though for it to drop what it's supposed to on a natural death such as burning.

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.
(Bug 1 Insta-Break) https://mega.nz/file/cIgVUYoZ#D2EIpWr-4bJ2B-I-VEsf7btH4gPOUlkg6i1pC5618Vc
(Bug 2 Mob not Dropping Drops) https://mega.nz/file/JNBgiajK#Qm91D7XGBo2FQ0KGbm0Vov2NL2l5knrIhBy6N07Jlns

**Server and Plugin Informations**
 - Installed plugins: (Attached picture)
![2020-07-27_18 25 24](https://user-images.githubusercontent.com/67762583/88598217-ce873400-d036-11ea-917f-76a42cf78bfd.png)

 - React Version: 6.634
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: 1.12.2 Paper Spigot (Latest)
 - Operating System (if applicable): I have no Idea

**Additional context**
No additional Context

**Comment by Frerduro** [comment]
We need some timings for the tps issue. Please do /timings on then /timings paste.

**Comment by AZFire1** [comment]
It turned out to be the plugin with the name TwerkingCrops. It was messing with a lot in the server. I removed it and it was all fine. Though, I would appreciate if in a couple of the next updates React could possibly have a fix to the stacking system not dropping drops? Other than that, it's all pretty cool. Maybe I just configured it wrong and that's why it's not dropping :)

**Comment by relavis** [comment]
Glad to see that the error was found!

I believe that there were many stacking fixes in the most recent updates of React as well.
