### ISSUE TITLE
React Supersampler Crash

### ISSUE THREAD

**Issue by ElBananaa** [VolmitSoftware/React#558]
**Describe the bug**
Hi! When I have react installed on my server, if a player connects to the server when it's empty, an error happens, and my server crash. 

**To Reproduce**
1. Install react on a server (I'm using react 6.634 & paper1.12.2 v1618)
2. Start the server
3. Leave the server on for several hours without anyone connecting to it (Sometimes, you need to wait few hours, sometimes it happens when you connect to the server 20 mins after the startup)
4. Connect to the server
5. The bug occurs

**Expected behavior**
Well, IDK, but everything except a crash ^^

**Screenshots or Video Recordings**
I don't have any screenshot

**Server and Plugin Informations**
 - Installed plugins: [https://gyazo.com/9e06f74c3d703109ecbc74dc9d2613da](https://gyazo.com/9e06f74c3d703109ecbc74dc9d2613da)
 - React Version: React 6.634
 - Server Platform and Version: Paper-1.12.2 v1618
 - Operating System (if applicable): Linux: Debian 10

**Complete Server Log**
[https://pastebin.com/EcsYBaHG](https://pastebin.com/EcsYBaHG)

**Additional context**
Unfortunately, I don't have any timings report (with react installed, and and when the crash occurs), but here's the react dump and the cpu-score:
Dump: https://hasteb.in/satevepu.json
Config: https://hasteb.in/omatayog.yml
Goals: https://hasteb.in/satevepu.json
CPU-Score (1 minute): [https://gyazo.com/09de9e325b16bb4f7d91b95e67316367](https://gyazo.com/09de9e325b16bb4f7d91b95e67316367)

My server is using latest aikar's jvm startup flags (adapted to my server's configuration), and is running under Java 11.0.8

I had this error on java 8, with older versions of react and spigot, and I had the same error. It only happens if react is installed.

Thanks,
Have a nice day!

**Comment by relavis** [comment]
Should be resolved in latest versions.
