### ISSUE TITLE
Warning on 1.16.2 startup

### ISSUE THREAD

**Issue by In77** [VolmitSoftware/React#567]
![_$Y%M~L4{1U@~ ~QK9{%8$6](https://user-images.githubusercontent.com/44344308/92318539-38d0c280-f040-11ea-897a-f1f3f6557321.png)

**Comment by In77** [comment]
Debian 10
JDK 8u251
Paper1.16.2 b184
React 6.636

**Comment by SwagPancakes** [comment]
I also have this problem in 1.16.2 Tuinity it says "No NMS Binder Found" but the plugin works fine.
I just want a clean console :<:<:<

**Comment by relavis** [comment]
Closed by 0187c18
