### ISSUE TITLE
1.16.4 R3 Not Working

### ISSUE THREAD

**Issue by xManInWhitex** [VolmitSoftware/React#572]
**Describe the bug**
The Plugin won't load on Paper 1.16.4 R3.

**To Reproduce**
Try to load the Plugin on a 1.16.4 R3 Spigot/Paper Server

**Expected behavior**
Load.

**Screenshots or Video Recordings**
https://pastebin.com/T9Y1ASkS

**Server and Plugin Informations**
Paper 1.16.4 B259
React 6.639

**Comment by hysrx** [comment]
Same occurrence for Paper 1.16.4 Build 261.

**Comment by Frerduro** [comment]
Plugin should be working for you guys now. Closing this now but feel free to comment or message on discord if you have further issues
