### ISSUE TITLE
No NMS Binder Found

### ISSUE THREAD

**Issue by EndlessLegends** [VolmitSoftware/React#575]
**Describe the bug**
I use papermc 253 build.
I bought it from version 6.639 yesterday and updated it to version 6.640 today.

**To Reproduce**
run

**Screenshots or Video Recordings**
![fuckingreact](https://user-images.githubusercontent.com/60249708/98546788-94d2f400-22da-11eb-8e2f-7fda153c0803.png)

**Server and Plugin Informations**
 - Installed plugins: 1(react)
 - React Version: 6.640
 - Server Platform and Version : paper-253(1.16.3)
 - Operating System (if applicable): win 10

**Additional context**
react warns me even alone without anything.

**Comment by relavis** [comment]
Fixed in 6.641
