### ISSUE TITLE
NoClassDefFoundError & ExceptionInInitializerError on server startup

### ISSUE THREAD

**Issue by In77** [VolmitSoftware/React#576]
**Describe the bug**
NoClassDefFoundError & ExceptionInInitializerError on server startup

**Screenshots or Video Recordings**
![image](https://user-images.githubusercontent.com/44344308/105477340-b0944680-5cdc-11eb-805e-d625d578016d.png)

**Server and Plugin Informations**
 - React Version: 6.641
 - Server Platform and Version: Paper 1.16.5 Build 439
 - Operating System : Debian 10

**Comment by relavis** [comment]
The second error shown is now fixed, will investigate the first error.

**Comment by relavis** [comment]
Fixed in 6.643 releasing tomorrow
