### ISSUE TITLE
Make React keep track of plugins that the server has but does not use.

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/React#578]
**Is your feature request related to a problem? Please describe.**
I believe that a really interesting feature to be added to react would be tracking unnecessary plugins or unused plugins on servers.
**Describe the solution you'd like**
a  command similar to /react plugins that gives you a book listing all the plugins that are not very commonly used or not used at all.

**Comment by TheDGOfficial** [comment]
How this can be determined though? Checking disabled plugins? I see no other way this can be determined. A plugin can also just be a shared library and do not interact with Bukkit in any way except main JavaPlugin registering, too.
