### ISSUE TITLE
React 6.645 NoClassDefFoundError at server start

### ISSUE THREAD

**Issue by In77** [VolmitSoftware/React#580]
**Describe the bug**
java.lang.NoClassDefFoundError: org/bstats/charts/CustomChart at server start

**Screenshots or Video Recordings**
![image](https://user-images.githubusercontent.com/44344308/106435684-2a32ee00-64ae-11eb-8c36-42b1849df15e.png)

**Server and Plugin Informations**
 - React Version:  6.645 
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: Paper 1.16.5 build 457
 - Operating System (if applicable): Debian 10

**Comment by relavis** [comment]
Fixed in 6.646
