### ISSUE TITLE
React generated an exception while executing task

### ISSUE THREAD

**Issue by Opalinium** [VolmitSoftware/React#583]
**Describe the bug**
This bug, as well as a number of other similar task execution exceptions, occurs every few minutes in the console on average.

**To Reproduce**
View the console while the server is running.

**Expected behavior**
I don't believe that anybody expects the console to be flooded by exception stack trace errors.

**Screenshots or Video Recordings
If applicable, add screenshots or video recordings to help explain your problem.**

**Server and Plugin Informations**

**Installed plugins:**
React Version: 6.646
Server Platform and Version [eg: PaperSpigot 1.14.4]: PaperSpigot 1.16.5
Operating System (if applicable): Linux Ubuntu Server 20.+
Additional context
![image](https://user-images.githubusercontent.com/58598304/107255045-c1d39780-69ec-11eb-9558-0803720b00a4.png)
![image](https://user-images.githubusercontent.com/58598304/107255388-17a83f80-69ed-11eb-9be9-fa2cfab01386.png)

**Comment by relavis** [comment]
Should be solved with latest version, please reopen if it is still occurring.
