### ISSUE TITLE
Scoreboard Flickers

### ISSUE THREAD

**Issue by AZFire1** [VolmitSoftware/React#585]
**Describe the bug**
The react scoreboard flickers a lot, it's kind of hard to look at. Could you change it to make it smoother?

**To Reproduce**
1. View the react scoreboard with /re score

**Screenshots or Video Recordings**

https://user-images.githubusercontent.com/67762583/107802142-bad7bc80-6d3f-11eb-8dab-fc0881069925.mp4

**Server and Plugin Informations**
 - Installed plugins: https://bin.bloom.host/ewivusorar.m
 - React Version: 6.646
 - Server Platform and Version: Purpur 1.16
 - Operating System (if applicable): Not applicable

**Comment by snuckdev** [comment]
Did you try with vanilla Spigot or Paper?

**Comment by AZFire1** [comment]
Yes, I just tried it with the latest version (6.647) with paperspigot. It was similar, though definitely not as much flickering, there was still some flickering though.

**Comment by relavis** [comment]
Fixed in 6.650
