### ISSUE TITLE
Can't download memory monitor.

### ISSUE THREAD

**Issue by Bengor-SkyEvo** [VolmitSoftware/React#586]
![image](https://user-images.githubusercontent.com/42621026/107874466-e223ba80-6ef4-11eb-9808-31bf84f04735.png)

Error message : 
![image](https://user-images.githubusercontent.com/42621026/107874480-ef40a980-6ef4-11eb-9162-a6daaaccc5b7.png)

As the title said, I got no idea with this.

**Comment by relavis** [comment]
What version of React are you using?

**Comment by relavis** [comment]
Closing, please respond with your React version to reopen this ticket.
