### ISSUE TITLE
Fast Leaf Decay only dropping oak saplings

### ISSUE THREAD

**Issue by DaMrZ** [VolmitSoftware/React#589]
**Describe the bug**
When fast leaf decay is enabled players are noticing an issue where only oak saplings are dropped instead of the correct sapling

**Server and Plugin Informations**
![image](https://user-images.githubusercontent.com/4590454/108597463-17ab2680-7381-11eb-9809-5687867b178c.png)

React Version: 6.65

Server Platform and Version:
git-Paper-466 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Operating System (if applicable):
Linux Debian 9

**Comment by AZFire1** [comment]
I agree with this issue ^^

**Comment by Billyds132** [comment]
Also getting this issue.

**Comment by stijnb1234** [comment]
https://github.com/VolmitSoftware/React/blob/4c9a9161a930653704719ba37daa64d226e7dac3/src/main/java/com/volmit/react/controller/FastDecayController.java#L41

Related to these lines. Uses the old Materials who do not exists anymore in 1.13+. Maybe move to the https://github.com/CryptoMorin/XSeries/ project for this?

New Materials: OAK_LEAVES, SPRUCE_LEAVES, BIRCH_LEAVES, JUNGLE_LEAVES, ACACIA_LEAVES, DARK_OAK_LEAVES

**Comment by relavis** [comment]
Fixed in upcoming version
