### ISSUE TITLE
repo.volmit.com is down

### ISSUE THREAD

**Issue by elliot-holley** [VolmitSoftware/React#592]
**Describe the bug**
no dependencies can be retrieved with gradle. errors indicate that it cannot contact repo.volmit.com
**To Reproduce**
1. run 'gradle build' at the root folder
2. wait about half a minute
3. look at something similar to [this](https://pastebin.com/ifs9PjUE)

**Expected behavior**
for the project to successfully compile.
**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Informations**
 - Installed plugins: N/A
 - React Version: latest available from this repo
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: N/A
 - Operating System (if applicable): Windows 10

**Additional context**
Add any other context about the problem here, server timings reports, React dump information, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by ArMiN231** [comment]
Should be fixed now. @relavis pls close this.
