### ISSUE TITLE
Fast Leaf Decay destroys persistant leaves

### ISSUE THREAD

**Issue by DestructivForce** [VolmitSoftware/React#594]
**Describe the bug**
Persistent (player placed) leaves decay, despite not doing so normally

**To Reproduce**
1. Place at least 2 leaf blocks adjacent to one another
2. break one
3. note that the other leaves are decaying

**Expected behavior**
Persistent leaves should not decay, to be consistent with vanilla behavior

**Server and Plugin Informations**
 - Installed plugins:
![image](https://user-images.githubusercontent.com/50807043/113054994-b04a7880-916f-11eb-8f4b-5140de292fe4.png)
 - React Version: 6.651
 - Server Platform and Version:
Purpur version git-Purpur-710 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by relavis** [comment]
Fixed in upcoming version
