### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Dreeam-qwq** [VolmitSoftware/React#595]
**Describe the bug**
```
Could not resolve: org.spigotmc.full:1.12.2:1.12.2
Could not resolve: org.bukkit.craftbukkit:1.16.2:1.16.2
Could not resolve: me.clip:placeholderapi:2.9.2
Could not resolve: com.boydti:fawe-api:latest
```

**To Reproduce**
1. import source
2. import gradle project
3. build react
4. See this error

**Expected behavior**

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Informations**
 - Installed plugins: none
 - React Version: the latest from repo
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: none
 - Operating System (if applicable): Windows Server 2016

**Additional context**
Add any other context about the problem here, server timings reports, React dump information, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by 360matt** [comment]
Add ``maven {url ='http://ci.athion.net/job/FastAsyncWorldEdit/ws/mvn/'}`` repository for FAWE.

I am also stuck for the two dependencies spigot full and bukkit 1.16.2

**Comment by stijnb1234** [comment]
Run BuildTools for 1.16.2. ;)

**Comment by 360matt** [comment]
> Run BuildTools for 1.16.2. ;)

And how to use it? Especially in this context with React?

**Comment by stijnb1234** [comment]
> > Run BuildTools for 1.16.2. ;)
> 
> And how to use it? Especially in this context with React?

https://www.spigotmc.org/wiki/buildtools/
