### ISSUE TITLE
Web based client

### ISSUE THREAD

**Issue by Kore-Development** [VolmitSoftware/React#596]
**Is your feature request related to a problem? Please describe.**
The React Remote Client is a legacy feature. I think it should be rewritten as a web based client.

**Describe the solution you'd like**
A web based React Remote Client

**Describe alternatives you've considered**
A rewrite of the desktop client?

**Additional context**

**Comment by relavis** [comment]
You mean like https://github.com/VolmitSoftware/ReactSynapse ?

**Comment by Kore-Development** [comment]
Didn't know that existed but yes

**Comment by relavis** [comment]
Duplicate of #529
