### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by QuintenQVD0** [VolmitSoftware/React#613]
**Building the project gives a class file version error **
when compiling the plugin i get a error off: 
  bad class file: /home/pi/.gradle/caches/modules-2/files-2.1/org.bukkit.craftbukkit/1.17/1.17/92a039b1e307af55262e6af94cdab7eef69bd958/1.17-1.17.jar(net/minecraft/core/IRegistry.class)
    class file has wrong version 60.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**To Reproduce**
1. install java 8 on linux and gradle 
2. go in to the /React folder
3. run gradle clean build

**Expected behavior**
 the class file shoud have version  52.0

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Informations**
 - React Version :6.655
 - Operating System (if applicable): linux rasbery pi os

**Additional context**
pi@raspberrypi:~/Documents/React $ gradle clean build
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :clean UP-TO-DATE
> Task :generateLombokConfig UP-TO-DATE
> Task :compileJava
/home/pi/Documents/React/src/main/java/primal/bukkit/nms/AdvancementHolder17.java:6: error: cannot access net.minecraft.core.IRegistry
import net.minecraft.core.IRegistry;
                         ^
  bad class file: /home/pi/.gradle/caches/modules-2/files-2.1/org.bukkit.craftbukkit/1.17/1.17/92a039b1e307af55262e6af94cdab7eef69bd958/1.17-1.17.jar(net/minecraft/core/IRegistry.class)
    class file has wrong version 60.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 18s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by StrangeOne101** [comment]
Minecraft 1.17 requires Java 16. Compiling on Java 8 will not work.

**Comment by ArMiN231** [comment]
https://github.com/VolmitSoftware/React/pull/614/files
