### ISSUE TITLE
React 5.4.2: (Spigot 1.12.2) /re configure bug

### ISSUE THREAD

**Issue by TheDevelon** [VolmitSoftware/React#73]
Hey cyberpwn, found an bug in /re configure.

First time, I configure any file over /re configure, all works fine. 
![image](https://user-images.githubusercontent.com/28627992/31249954-937ae668-aa19-11e7-9433-f51bce631999.png)

After the first configuration, the inventory updates and I can move any items in my inventory and nothing happens.
![image](https://user-images.githubusercontent.com/28627992/31250037-d0267c26-aa19-11e7-89c0-25bf5af5321f.png)

Best regards,
TheDevelon.

PS: Dont judge me for my english, I am from Germany.^^

**Comment by cyberpwnn** [comment]
Some configurable options cannot be changed (config.yml) but the ones you are showing should change.

The new configuration for React6 will be simpler and works with hotloading better.
