### ISSUE TITLE
Plugin crash: /re reload

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#78]
React crash when we reload it:
https://hastebin.com/iguyoyacil.vbs

Server Version: PaperSpigot 1.8.8

**Comment by CaptainAmpersand** [comment]
Still present in 6.24129a
Server Version: Spigot 1.12.2 latest release
https://hastebin.com/uvobecanek.vbs

**Comment by cyberpwnn** [comment]
Refer to #126
