### ISSUE TITLE
[React6] Re Status book doesn't exit inventory

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#83]
The react books used to leave your inventory when you clicked on them as it is old information. It appears as if, now, they do not. Not sure if a feature or not :P

Also, there is no message when you do /re status. I ended up getting 5 books without noticing.

Currently on 1.12.2 Spigot version git-Spigot-549c1fa-2ee49b4 (MC: 1.12.2)

**Comment by cyberpwnn** [comment]
Fixed in 6.14168a
