### ISSUE TITLE
[R6] NoShuchMethodeError: isCustomNameVisible 

### ISSUE THREAD

**Issue by GwnDaan** [VolmitSoftware/React#86]
When running /re act cull-entities: http://prntscr.com/huh9h6

Server Version: 1.7.10 spigot (NOT paperspigot)
React: v6.13026a

**Comment by cyberpwnn** [comment]
1.7.10 caused it, ill add a feature check for that. Thanks for the report!

**Comment by cyberpwnn** [comment]
Resolved in 6.14168a
