### ISSUE TITLE
[R6] NullPointerException when stopping

### ISSUE THREAD

**Issue by GwnDaan** [VolmitSoftware/React#89]
When you stop the server directly after you start it up, this error appears: https://gyazo.com/329faa415872300ba544b15e341e700f

Server: 1.12.2 Spigot
React Version: v6.14168a

**Comment by cyberpwnn** [comment]
You can paste the issue in github. Just use formatting like this

```
code in here
```

Made like this (using `)

![image](https://user-images.githubusercontent.com/10619135/34638973-d8d28896-f2a4-11e7-896c-c826686e9745.png)

**Comment by cyberpwnn** [comment]
Fixed on 6.14742a
