### ISSUE TITLE
NoSuchElementException: null

### ISSUE THREAD

**Issue by GwnDaan** [VolmitSoftware/React#90]
Server crashed after a few errors.

Console: https://pastebin.com/0RKMDXap
Server: 1.12.2 Spigot
React: v6.14168a

**Comment by cyberpwnn** [comment]
Not sure what the cause is. Maybe its caused due to #91 so ill push out 6.14742a before trying to fix this one.

**Comment by cyberpwnn** [comment]
Fixed in 6.15201a
